<div class="container">
	<input type="text"></input>
	<input type="date" class="datepicker">
</div>
<script type="text/javascript">
	$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    multidate: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });



$(window).resize(function() {
	var viewportWidth = $(window).width();
	var viewportHeight = $(window).height();
	console.log( viewportWidth + "|" + viewportHeight);
});
</script>


<?php
echo date('D, M j, Y h:i:s a', strtotime('-30 days'));

?> 
