<div class="container">
	<input type="text"></input>
	<input type="date" class="datepicker">
</div>
<script type="text/javascript">
	$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    multidate: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
</script>


<?php
echo strpos("I love php, ew I love php too!","New");
?> 