<div class="container">
	<div class="col m12">
		<table class="responsive-table highlight centered">
		<thead>
		  <tr>
			  <th>Type</th>
			  <th>Value</th>
		  </tr>
		</thead>

		<tbody>
		  <tr>
			<td>Battery Level</td>
			<td><span id="batlvl">0</span></td>
		  </tr>
		</tbody>
	  </table>
	</div>
</div>

<script type="text/javascript">
	navigator.getBattery().then(function(battery) {
  function updateAllBatteryInfo(){
	updateChargeInfo();
	updateLevelInfo();
	updateChargingInfo();
	updateDischargingInfo();
  }
  updateAllBatteryInfo();

  battery.addEventListener('chargingchange', function(){
	updateChargeInfo();
  });
  function updateChargeInfo(){
	console.log("Battery charging? "
				+ (battery.charging ? "Yes" : "No"));
  }

  battery.addEventListener('levelchange', function(){
	updateLevelInfo();
  });
  function updateLevelInfo(){
	// console.log("Battery level: "
	// 			+ battery.level * 100 + "%");
	document.getElementById("batlvl").innerHTML = battery.level * 100 + "%";
  }

  battery.addEventListener('chargingtimechange', function(){
	updateChargingInfo();
  });
  function updateChargingInfo(){
	console.log("Battery charging time: "
				 + battery.chargingTime + " seconds");
  }

  battery.addEventListener('dischargingtimechange', function(){
	updateDischargingInfo();
  });
  function updateDischargingInfo(){
	console.log("Battery discharging time: "
				 + battery.dischargingTime + " seconds");
  }

});
</script>