<style type="text/css">
	.hide {
		display: none;
	}
	.show {
		display: block;
	}
</style>
<script type="text/javascript">
	if( !('serviceWorker' in navigator) ) {
		console.log("Service Worker: is not working!");
	}else{
		console.log("Service Worker: is running properly!");
		$("#serviceWorker").addClass("show");
	}

	if( !("PushManager" in window) ) {
		console.log("Push Manager: is not supported!");
	}else{
		console.log("Push Manager: is up and running!");
		$("#pushManager").addClass("show");
	}

	function registerServiceWorker() {
		return navigator.serviceWorker.register("lexi-service.js")
		.then(function(registration) {
			console.log("Service worker successfully registered");
			return register;
		})
		.catch(function(err){
			console.error("Unable to register service worker.", err);
		});
	}

	function askPermission() {
		return new Promise(function( resolve, reject ) {
			const permissionResultl = Notification.requestPermission(function( result ) {
				resolve( result );
			});
			if(permissionResult) {
				permissionReuslt.then( resolve, reject );
			}
		})
		.then(function( permissionReuslt ) {
			if( permissionReuslt !== 'granted' ) {
				throw new Error( "We weren't granted permission" );
			}
		});
	}

	registerServiceWorker();
	askPermission();
</script>

<span id="serviceWorker" class="hide" style="color: green;">Service Worker is not working!</span><br>
<span id="pushManager" class="hide" style="color: green;">Push Manager is not supported in this browser.</span><br>