<!--  Tables Section-->
	  <div id="login" class="row">
	  <!-- <h1 class="thin">Login</h1> -->
	<div class="col s12 m8 l6 offset-m2 offset-l3 card-panel">
	  <form name="frmLogin" id="frmLogin" action="<?=Core::getBaseUrl()?>account/login/authenticate" method="POST" class="login-form">
	  <?php
		$http = Core::getSingleton("url/request");
		if( $http->getRequest("redirect") ) {
		?>
			<input type="hidden" name="redirect" value="<?=$http->getRequest("redirect")?>">
		<?php
		}
	  ?>
		<div class="row primary-color form-header">
		  <div class="col s4">
			<img src="<?=$this->getImage('admin/logo.png');?>" alt="logo" class="logo responsive-img-height">
		  </div>
		  <div class="col s8 right-align">
			<h4 class="light white-text">Login</h4>
		  </div>
		</div>
		<div class="form-body">
	<?php $this->getChildBlock("page/alert"); ?>
		<div class="row">
		  <div class="input-field col s12">
			<i class="mdi-social-person prefix"></i>
			<input id="username" name="username" type="text" class="validate">
			<label for="username" class="center-align">Username</label>
		  </div>
		</div>
		<div class="row">
		  <div class="input-field col s12">
			<i class="mdi-action-lock prefix"></i>
			<input id="password" name="password" type="password">
			<label for="password">Password</label>
		  </div>
		</div>
		<div class="row">
		  <div class="input-field col s6">
			<input type="submit" name="btnLogin" class="btn waves-effect waves-light col s12" value="Login">
		  </div>
		  <div class="input-field col s6">
			<a href="<?=Core::getBaseUrl()?>" class="btn waves-effect waves-light col s12">Cancel</a>
		  </div>
		</div>
		<!-- <div class="row">
		  <div class="col s6">
			<p class="margin medium-small"><a href="<?=Core::getBaseUrl()?>account/register">Register Now!</a></p>
		  </div>
		  <div class="col s6">
			  <p class="margin right-align medium-small"><a href="<?=Core::getBaseUrl()?>account/resetpassword">Forgot password?</a></p>
		  </div>          
		</div> -->
	  </div>
	  </form>
	</div>
  </div>

<script type="text/javascript">
  $("#frmLogin").validate({
        rules: {
            username: {
                required: true,
                minlength: 5
            },
            password: {
        required: true,
        minlength: 5
      },
    	cgender:"required",
      cagree:"required",
        },
        //For custom messages
        messages: {
            uname:{
                required: "Enter a username",
                minlength: "Enter at least 5 characters"
            },
        },
        errorElement : 'div',
        errorPlacement: function(error, element) {
          var placement = $(element).data('error');
          if (placement) {
            $(placement).append(error)
          } else {
            error.insertAfter(element);
          }
        }
     });
</script>