<!-- Personal tab START -->
<div id="personal">
	<form name="frmPersonal" action="/account/profile/update" method="POST" id="frmPersonal">
		<div class="form-pad">
			<div class="row">
				<div class="col s12 m8 push-m4">
					<!-- Personal info FIELDS -->
					<div class="input-field">
						<input id="fname" name="fname" type="text" class="validate" value="Mashiro">
						<label for="fname">First Name</label>
					</div>
					<div class="input-field">
						<input id="lname" name="lname" type="text" class="validate" value="Alexis">
						<label for="lname">Last Name</label>
					</div>
					<div class="input-field">
						<input id="contact" name="contact" type="text" class="validate" value="+63 090 6149 8612" required>
						<label for="contact">Phone</label>
					</div>
					<div class="input-field">
						<input id="email" name="email" type="email" class="validate" value="alexis(at)arkhold.com">
						<label for="email" data-error="wrong" data-success="right">Email</label>
					</div>
					<div class="input-field with-note">
						<input id="skill" name="skill" type="text" class="validate" value="html, css, sass, js, php or anything lol!">
						<label for="skill">Skills</label>
						<span class="note">Please, provide comma separated list.</span>
					</div>
					<div class="input-field">
						<textarea id="about" name="about" class="materialize-textarea">Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. </textarea>
						<label for="about">About</label>
					</div>
					<div class="input-field">
						<input placeholder="http://www.arkhold.com" id="weburl" type="text" class="validate">
						<label for="weburl">Website Url</label>
					</div>
				</div>
				<div class="col s12 m4 pull-m8">
					<!-- Personal info PROFILE PHOTO -->
					<div class="form-pad center-align">
						<img class="responsive-img circle" src="<?=$this->getImage('default/defaultprofile.jpg');?>">
						<div class="file-field input-field">
							<div class="btn no-float primary-color">
								<i class="material-icons large">file_upload</i>
								<input type="file" name="profileImage">
							</div>
							<div class="file-path-wrapper hide">
								<input class="file-path validate center-align" type="text">
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Save Cancel -->
			<div class="row">
			<div class="col s12 m8 push-m4 buttons">
			<button class="waves-effect waves-light btn" type="submit" name="btnSavePersonal"><i class="material-icons right">done</i>Save changes</button>
			<button class="waves-effect waves-light btn blue-grey lighten-2" type="submit" name="btnCancelPersonal"><i class="material-icons right">clear</i>Cancel</button>
			</div>
			</div>
		</div>
	</form>
</div>
<!-- Personal tab END -->