<!--  Tables Section-->
      <div id="login" class="row">
	  <!-- <h1 class="thin">Login</h1> -->
    <div class="col s12 m8 l6 offset-m2 offset-l3 card-panel">
      <form class="login-form">
        <div class="row primary-color form-header blue-grey darken-3">
          <div class="col s4">
            <img src="<?=$this->getImage('default/admin-logo-full.svg');?>" alt="logo" class="logo responsive-img-height">
          </div>
		  <div class="col s8 right-align">
            <h4 class="light white-text">Register</h4>
          </div>
        </div>
		<div class="form-body">
        <div class="row">
          <div class="input-field col s12">
            <i class="mdi-social-person prefix"></i>
            <input id="username" type="text" class="validate">
            <label for="username" class="center-align">Username</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="mdi-communication-email prefix"></i>
            <input id="email" type="email" class="validate">
            <label for="email" class="center-align">Email</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="mdi-action-lock prefix"></i>
            <input id="password" type="password" class="validate">
            <label for="password">Password</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="mdi-action-lock prefix"></i>
            <input id="password-again" type="password">
            <label for="password-again">Re-type password</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <a href="register.html" class="btn-large waves-effect waves-light col s12">Register Now</a>
          </div>
          <div class="input-field col s12">
            <p class="center medium-small sign-up">Already registered? <a href="/account/login">Login</a></p>
          </div>
        </div>
	  </div>
      </form>
    </div>
  </div>