<?php
$session = Core::getSingleton("system/session");
// $session->add("alert", [
// 	"type" => "error",
// 	"body" => "This message was generated because some error were detected while processing your request."
// ]);
?>

<?php
	if( isset($_SESSION["alert"]) ) {
		$alert = $_SESSION["alert"];
		$setup = [
			"error" 	=> "red darken-3",
			"warning" 	=> "orange darken-3",
			"success" 	=> "green darken-3",
			"info" 		=> "blue darken-3"
		];
?>
		<div class="row">
			<div class="col s12 m12">
				<div class="card-panel <?=$setup[$alert['type']]?>">
					<span style="color: white;">
						<?=ucfirst($alert["type"])?> : <br>
						<?=$alert["message"]?>
					</span>
				</div>
			</div>
		</div>
<?php
		unset($_SESSION["alert"]);
	}

?>