<nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg " color-on-scroll="100" id="sectionsNav">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" href="<?=Core::getBaseUrl()?>">LexiPHP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    <span class="navbar-toggler-icon"></span>
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="dropdown nav-item">
                        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                            <i class="material-icons">apps</i> Account
                        </a>
                        <div class="dropdown-menu dropdown-with-icons">
                            <a href="<?=Core::getBaseUrl()?>account/profile" class="dropdown-item">
                                <i class="material-icons">account_circle</i> Profile
                            </a>
                            <a href="<?=Core::getBaseUrl()?>account/logout" class="dropdown-item">
                                <i class="material-icons">account_circle</i> Logout
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>