<header class="no-padding">
		<div class="navbar-fixed">  
		  <nav class="navfeature">
			  <div class="container nav-wrapper">
				<a href="<?=Core::getBaseUrl()?>" class="waves-effect waves-light">
						<span class="hide-on-small-only"><img src="<?=$this->getImage("admin/logo.png")?>" width="30" id="appicon" style="vertical-align: middle;margin-bottom:10px;margin-right:10px;"></span>
						<span id="header-large" style="font-weight:300;font-size:1.3rem;">Teacher Evaluation System</span>
				</a>
				
<ul id="nav-mobile" class="hide-on-med-and-down right"><li id="menu-item-24" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-5 current_page_item menu-item-24"><a href="<?=Core::getBaseUrl()?>">Home</a></li>
<li id="menu-item-985" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-985"><a class="modal-trigger" href="#modalMission">Mission</a></li>
<li id="menu-item-1150" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1150"><a class="modal-trigger" href="#modalVision">Vision</a></li>
<li id="menu-item-1150" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1150"><a href="<?=Core::getBaseUrl()?>evaluation">Evaluate</a></li>
<li id="menu-item-1204" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1204"><a href="<?=Core::getBaseUrl()?>account/login">Login</a></li>
</ul>				
				<a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi mdi-menu"></i></a>
			  </div>
		  </nav>
		</div>
		<div class="side-nav-start">
		  <ul id="slide-out" class="side-nav"><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-5 current_page_item menu-item-24"><a href="index.html">App</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-985"><a href="https://www.kbremote.net/Home/Start">Remote Management</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1150"><a href="#support">Support</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1204"><a href="#contact">Contact</a></li>
</ul>		</div>
	</header>

<!-- Modal Structure -->
  <div id="modalMission" class="modal">
    <div class="modal-content">
      <h4 style="color: #444444;" class="center">Mission</h4>
      <p>The University shall primarily provide advanced education, higher professional and technological instruction and training in the fields of agriculture, arts and sciences, business and industry, computer and information technology, education, engineering, environmental sciences, fishery, forestry, law and criminal justice, medicine and allied sciences, and other related fields of study. It shall intensify its research and extension, and production functions and provide progressive leadership in its area of specialization.</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Okay</a>
    </div>
  </div>

 <!-- Modal Structure -->
  <div id="modalVision" class="modal">
    <div class="modal-content">
      <h4 style="color: #444444;" class="center">Vision</h4>
      <p>A synergistic multi-campus university producing competent, value-laden and globally competitive graduates who are proactive in promoting the economic prosperity of the country.</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Okay</a>
    </div>
  </div>