<style type="text/css">
	.side-nav li.logo {
		background-color: #4c636e;
	}
</style>
<!-- Header START -->
<header> 
  <!-- Navigation Bar on the top, for medium and small devices -->
  <div class="brand-logo hide-on-large-only"><img src="<?=$this->getImage('default/admin-logo-full.svg');?>" alt="logo" class="logo responsive-img"></div>
  <div class="navbar-fixed hide-on-large-only">
	<nav>
	  <div class="nav-wrapper">
		<ul class="right">
		  <li class="hide-on-small-only"><a href="#search-in-modal" class="modal-trigger"><i class="material-icons">search</i></a></li>
		  <li class="hide-on-small-only"><a href="account.html"><i class="material-icons">perm_identity</i></a></li>
		  <li class="hide-on-small-only"><a href="login.html" target="_blank"><i class="material-icons">exit_to_app</i></a></li>
		  <li class="toogle-side-nav"><a href="#" data-activates="slide-menu" class="button-collapse"><i class="material-icons">menu</i></a></li>
		</ul>
	  </div>
	</nav>
  </div>
  <!-- Side Navigation - fixed for large (nice scroll with Simplebar plugin), slide/drag for medium and small devices -->
  <div id="slide-menu" class="side-nav fixed" data-simplebar-direction="vertical">
	<ul class="side-nav-main">
	  <li class="logo hide-on-med-and-down"><img src="<?=$this->getImage('default/admin-logo-full.svg');?>" alt="logo" class="logo responsive-img"></li>
		<li class="side-nav-inline hide-on-med-only"> 
			<a href="/account/login/exit" class="inline waves-effect tooltipped" data-position="bottom" data-delay="50" data-tooltip="Logout">
				<i class="mdi-action-exit-to-app"></i>
			</a> 
			<a href="/account/profile" class="inline waves-effect tooltipped" data-position="bottom" data-delay="50" data-tooltip="Profile">
				<i class="mdi-action-perm-identity"></i>
			</a> 
			<a href="#search-in-modal" class="inline waves-effect modal-trigger">
				<i class="mdi-action-search"></i>
			</a>
		</li>
	  <li><a href="/" class="waves-effect"><i class="mdi-action-dashboard left"></i><span>Dashboard</span></a></li>
	  <li><a href="messages.html" class="waves-effect"><i class="mdi-communication-email left"></i><span>Messages</span><span class="new badge">3</span></a></li>
	  <li>
		<ul class="collapsible" data-collapsible="accordion">
		  <li><a class="collapsible-header waves-effect"><i class="mdi-action-description left"></i><span>Pages</span><span class="neutral badge">4</span></a>
			<div class="collapsible-body">
			  <ul>
				<li><a href="account.html">Account</a></li>
				<li class="divider"></li>
				<li><a href="login.html" target="_blank">Login</a></li>
				<li class="divider"></li>
				<li><a href="register.html" target="_blank">Register</a></li>
				<li class="divider"></li>
				<li><a href="reset-password.html" target="_blank"><span>Reset Password</span></a></li>
			  </ul>
			</div>
		  </li>
		  <li><a class="collapsible-header waves-effect"><i class="mdi-editor-format-paint left"></i><span>CSS</span></a>
			<div class="collapsible-body">
			  <ul>
				<li><a href="css-colors.html">Colors</a></li>
				<li class="divider"></li>
				<li><a href="css-typo.html">Typography</a></li>
				<li class="divider"></li>
				<li><a href="css-grid.html"><span>Grid</span><span class="neutral badge">12</span></a></li>
				<li class="divider"></li>
				<li><a href="css-shadow.html">Shadow</a></li>
				<li class="divider"></li>
				<li><a href="css-media.html">Media</a></li>
				<li class="divider"></li>
				<li><a href="css-table.html">Table</a></li>
				<li class="divider"></li>
				<li><a href="css-helpers.html">Helpers</a></li>
			  </ul>
			</div>
		  </li>
		  <li><a class="collapsible-header waves-effect"><i class="mdi-av-web left"></i><span>Elements</span></a>
			<div class="collapsible-body">
			  <ul>
				<li><a href="ui-badges-chips.html">Badges & Chips</a></li>
				<li class="divider"></li>
				<li><a href="ui-buttons.html">Buttons</a></li>
				<li class="divider"></li>
				<li><a href="ui-cards.html">Cards</a></li>
				<li class="divider"></li>
				<li><a href="ui-collections.html">Collections</a></li>
				<li class="divider"></li>
				<li><a href="ui-forms.html">Forms</a></li>
				<li class="divider"></li>
				<li><a href="ui-icons.html"><span>Icons</span><span class="neutral badge">740+</span></a></li>
				<li class="divider"></li>
				<li><a href="ui-navigations.html">Navigations</a></li>
				<li class="divider"></li>
				<li><a href="ui-preloaders.html">Preloaders</a></li>
			  </ul>
			</div>
		  </li>
		  <li><a class="collapsible-header waves-effect"><i class="mdi-action-extension left"></i><span>Javascripts</span></a>
			<div class="collapsible-body">
			  <ul>
				<li><a href="js-collapsible.html">Collapsible</a></li>
				<li class="divider"></li>
				<li><a href="js-dialogs.html">Dialogs</a> </li>
				<li class="divider"></li>
				<li><a href="js-dropdown.html">Dropdown</a> </li>
				<li class="divider"></li>
				<li><a href="js-media.html">Media</a> </li>
				<li class="divider"></li>
				<li><a href="js-modals.html">Modals</a> </li>
				<li class="divider"></li>
				<li><a href="js-parallax.html">Parallax</a> </li>
				<li class="divider"></li>
				<li><a href="js-pushpin.html">Pushpin</a> </li>
				<li class="divider"></li>
				<li><a href="js-scrollfire.html">ScrollFire</a> </li>
				<li class="divider"></li>
				<li><a href="js-scrollspy.html">Scrollspy</a> </li>
				<li class="divider"></li>
				<li><a href="js-sidenav.html">SideNav</a> </li>
				<li class="divider"></li>
				<li><a href="js-tabs.html">Tabs</a> </li>
				<li class="divider"></li>
				<li><a href="js-transitions.html">Transitions</a> </li>
				<li class="divider"></li>
				<li><a href="js-waves.html">Waves</a> </li>
			  </ul>
			</div>
		  </li>
		</ul>
	  </li>
	  <li><a href="sass.html" class="waves-effect"><i class="mdi-action-settings left"></i><span>SASS</span></a></li>
	  <li><a href="extra.html" class="waves-effect"><i class="mdi-action-thumb-up left"></i><span>Extra</span><span class="alert badge"></span></a></li>
	</ul>
  </div>
  <!-- Search in Modal START -->
  <div id="search-in-modal" class="modal">
	<div class="modal-content">
	  <nav class="flat">
		<div class="nav-wrapper">
		  <form>
			<div class="input-field">
			  <input id="search" type="search" class="secondary-color-text white" style="margin:0;" required>
			  <label for="search"><i class="material-icons secondary-color-text">search</i></label>
			  <i class="material-icons modal-action modal-close">close</i> </div>
		  </form>
		</div>
	  </nav>
	</div>
	<div class="modal-footer"> <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Search now</a> </div>
  </div>
  <!-- Search in Modal END --> 
</header>
<!-- Header END --> 