<header class="no-padding">
		<div class="navbar-fixed">  
		  <nav class="navfeature">
			  <div class="container nav-wrapper">
				<a href="index.html" class="waves-effect waves-light">
						<span class="hide-on-small-only"><img src="<?=$this->getImage("admin/logo.png")?>" width="30" id="appicon" style="vertical-align: middle;margin-bottom:10px;margin-right:10px;"></span>
						<span id="header-large" style="font-weight:300;font-size:1.3rem;">Teacher Evaluation System</span>
				</a>
				
<ul id="nav-mobile" class="hide-on-med-and-down right"><li id="menu-item-24" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-5 current_page_item menu-item-24"><a href="<?=Core::getBaseUrl()?>">Home</a></li>
<li id="menu-item-985" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-985"><a href="#">Mission</a></li>
<li id="menu-item-1150" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1150"><a href="#">Vision</a></li>
<li id="menu-item-1150" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1150"><a href="<?=Core::getBaseUrl()?>evaluation">Evaluate</a></li>
<li id="menu-item-1204" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1204"><a href="<?=Core::getBaseUrl()?>account/login">Login</a></li>
</ul>				
				<a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi mdi-menu"></i></a>
			  </div>
		  </nav>
		</div>
		<div class="side-nav-start">
		  <ul id="slide-out" class="side-nav"><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-5 current_page_item menu-item-24"><a href="index.html">App</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-985"><a href="https://www.kbremote.net/Home/Start">Remote Management</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1150"><a href="#support">Support</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1204"><a href="#contact">Contact</a></li>
</ul>		</div>
	</header>