<!-- Preloader START -->
<div class="stage-wrapper">
    <div class="stage">
      	
    <div class="preloader-wrapper big active">
      <div class="spinner-layer">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
    </div>
	
    </div>
</div>
<!-- Preloader END -->