<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/nav"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<!-- Main START -->
<main>
  <div class="container">
    <h1 class="thin">Criteria</h1>
    <!--  Tables Section-->
    <div id="messages" class="mailbox section">
      <div class="row">
        <div class="col s12">
		  <div class="z-depth-1">
		    <ul class="tabs account">
                <li class="col s4 tab"><a class="active" href="#personal">Criteria</a></li>
                <li class="col s4 tab"><a href="#password">Sub Criteria</a></li>
                <li class="col s4 tab"><a href="#privacy">Privacy</a></li>
            </ul>
		  </div>
        </div>
        <div class="col s12">
          <div class="card-panel no-padding">
		  
          	<!-- Add criteria childblock -->
          	<?php $this->getChildBlock("admin/addcriteria"); ?>

		   <!-- Password tab START -->
		   <div id="password">
		   <form>
		   <div class="form-pad">
		    <div class="row">
				<div class="col s12">
					<div class="input-field">
						<input id="current" type="password" class="validate">
						<label for="current">Current Password</label>
					</div>
					<div class="input-field">
						<input id="new" type="password" class="validate">
						<label for="new">New Password</label>
					</div>
					<div class="input-field">
						<input id="re-type-new" type="password" class="validate">
						<label for="re-type-new">Re-type New Password</label>
					</div>
					<div class="buttons">
						<button class="waves-effect waves-light btn" type="submit" name="action1"><i class="material-icons right">done</i>Save changes</button>
						<!-- <button class="waves-effect waves-light btn blue-grey lighten-2" type="submit" name="action2"><i class="material-icons right">clear</i>Cancel</button> -->
					</div>
				</div>
			</div>
		   </div>
		   </form>
		   </div>
		   <!-- Password tab END -->
		   <!-- Privacy tab START -->
		   <div id="privacy">
		   <form>
		   <div class="form-pad">
		    <div class="row">
				<div class="col s12">
				      <div class="row" style="margin-top: 20px;">
						<!-- Switch Title -->
						<div class="col s12 m8">
							<span>Pariatur prehenderit enim eiusmod</span>
						</div>
						<!-- Switch -->
						<div class="col s12 m4">
						  <div class="switch right">
							<label>
								Off
								<input type="checkbox" checked="checked">
								<span class="lever"></span>
								On
							</label>
						  </div>
					    </div>
					  </div>
					  <div class="divider"></div>
					  <div class="row" style="margin-top: 20px;">
						<!-- Switch Title -->
						<div class="col s12 m8">
							<span>Suspendisse nisi sem</span>
						</div>
						<!-- Switch -->
						<div class="col s12 m4">
						  <div class="switch right">
							<label>
								Off
								<input type="checkbox">
								<span class="lever"></span>
								On
							</label>
						  </div>
					    </div>
					  </div>
					  <div class="divider"></div>
					  <div class="row" style="margin-top: 20px;">
						<!-- Switch Title -->
						<div class="col s12 m8">
							<span>Ut vestibulum nunc convallis</span>
						</div>
						<!-- Switch -->
						<div class="col s12 m4">
						  <div class="switch right">
							<label>
								Off
								<input type="checkbox" checked="checked">
								<span class="lever"></span>
								On
							</label>
						  </div>
					    </div>
					  </div>
					  <div class="divider"></div>
					  <div class="row" style="margin-top: 20px;">
						<!-- Switch Title -->
						<div class="col s12 m8">
							<span>Cras vitae lobortis lectus</span>
						</div>
						<!-- Switch -->
						<div class="col s12 m4">
						  <div class="switch right">
							<label>
								Off
								<input type="checkbox" checked="checked">
								<span class="lever"></span>
								On
							</label>
						  </div>
					    </div>
					  </div>
					  <div class="divider"></div>
					  <div class="row" style="margin-top: 20px;">
						<!-- Switch Title -->
						<div class="col s12 m8">
							<span>Cras laoreet dui</span>
						</div>
						<!-- Switch -->
						<div class="col s12 m4">
						  <div class="switch right">
							<label>
								Off
								<input type="checkbox">
								<span class="lever"></span>
								On
							</label>
						  </div>
					    </div>
					  </div>
					  <div class="divider"></div>
					<div class="buttons" style="margin-top: 20px;">
						<button class="waves-effect waves-light btn" type="submit" name="action1"><i class="material-icons right">done</i>Save changes</button>
						<button class="waves-effect waves-light btn blue-grey lighten-2" type="submit" name="action2"><i class="material-icons right">clear</i>Cancel</button>
					</div>
				</div>
			</div>
		   </div>
		   </form>
		   </div>
		   <!-- Privacy tab END -->
		  </div>
        </div>
      </div>
    </div>
  </div>
  <!-- container END --> 
  
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>