<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/navdean"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<div class="container">
	<h1 class="thin">Dean Dashboard</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row">
			<div class="col s12" style="color: black;">
				<h5><b>Dept: </b>College of ICT</h5>
			</div>
		</div>
		<div class="row ">
			<form>
				<div class="input-field col s2">
					<select>
						<!-- <option value="" disabled selected>Choose your option</option> -->
						<?php
							foreach( Core::getSingleton("evaluation/evaluation")->getSchoolYear() as $scyear ) {
								?>
									<option value="<?=$scyear?>" ><?=$scyear?></option>
								<?php
							}
						?>
					</select>
					<label>School Year</label>
				</div>
				<div class="input-field col s2">
					<select>
						<?php
							foreach( Core::getSingleton("evaluation/evaluation")->getSemester() as $sem ) {
								?>
								<option value="<?=$sem?>"><?=$sem?></option>
								<?php
							}
						?>
					</select>
					<label>Semester</label>
				</div>
				<div class="input-field col s2">
					<input type="submit" class="btn" name="btnSubmit" value="Go">
				</div>
			</form>
		</div>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light center" style="color: white;">
								List Of Faculty
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							<div class="container">
								<table style="margin: 15px;" class="highlight centered">
								<thead>
								  <tr>
									  <th>Name</th>
									  <th>Faculty</th>
									  <th>Status</th>
									  <th>Action</th>
								  </tr>
								</thead>

								<tbody>
									<?php
										foreach( Core::getModel("account/account")->where("account_type_id", 3)->get() as $account ) {
											?>
											<tr>
												<td><?=$account->fname?> <?=$account->lname?></td>
												<td><?=Core::getModel("account/accounttype")->getAccountType($account->account_type_id)->type?></td>
												<td><?= $account->status ?></td>
												<td>
													<!-- <a href="<?=Core::getBaseUrl()?>admin/evaluation/view/teacher/1/id/<?=$account->id?>">View</a> --> 
													<a class="modal-trigger" href="#modal<?=$account->id?>">View</a> |
													<a href="#">Edit</a> |
													<a href="<?=Core::getBaseUrl()?>admin/evaluation/evaluate/id/<?=$account->id?>">Evaluate</a>
													
												</td>
													<!-- Modal Trigger -->
													

														<!-- Modal Structure -->
														  <div id="modal<?=$account->id?>" class="modal">
														    <div class="modal-content center">
														    	<a href="<?=Core::getBaseUrl()?>admin/evaluation/view/student/1/id/<?=$account->id?>" class="btn" style="width: 185px;">Student</a>
														    	<a href="<?=Core::getBaseUrl()?>admin/evaluation/view/peer/1/id/<?=$account->id?>" class="btn" style="width: 185px;">Peer</a>
														    </div>
														    <!-- <div class="modal-footer">
														      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
														    </div> -->
														  </div>
											</tr>
											<?php
										}
									?>
									
								</tbody>
								</table>
							</div>
						</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>
