<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/navdean"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<div class="container">
	<h1 class="thin">Dean Dashboard</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row">
			<div class="col s12" style="color: black;">
				<h5><b>Dept: </b>College of ICT</h5>
			</div>
		</div>
		<div class="row ">
			<form>
				<div class="input-field col s2">
					<select>
						<option value="" disabled selected>Choose your option</option>
						<option value="1">2017-2018</option>
						<option value="1">2017-2018</option>
						<option value="1">2017-2018</option>
						<option value="1">2017-2018</option>
						<option value="1">2017-2018</option>
					</select>
					<label>School Year</label>
				</div>
				<div class="input-field col s2">
					<select>
						<option value="" disabled selected>Choose your option</option>
						<option value="1">1st sem</option>
						<option value="2">2nd sem</option>
					</select>
					<label>Semester</label>
				</div>
				<div class="input-field col s2">
					<input type="submit" class="btn" name="btnSubmit" value="Go">
				</div>
			</form>
		</div>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light center" style="color: white;">
								List Of Faculty
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							<div class="container">
								<table style="margin: 15px;" class="highlight centered">
								<thead>
								  <tr>
									  <th>Name</th>
									  <th>Faculty</th>
									  <th>Status</th>
									  <th>Action</th>
								  </tr>
								</thead>

								<tbody>
									<?php
										foreach( Core::getModel("account/account")->where("account_type_id", 3)->get() as $account ) {
											?>
											<tr>
												<td><?=$account->fname?> <?=$account->lname?></td>
												<td><?=Core::getModel("account/accounttype")->getAccountType($account->account_type_id)->type?></td>
												<td><?= $account->status ?></td>
												<td>
													<a href="<?=Core::getBaseUrl()?>admin/evaluation/view">View</a> |
													<a href="#">Edit</a> |
													<a href="<?=Core::getBaseUrl()?>admin/evaluation/evaluate">Evaluate</a>
												</td>
											</tr>
											<?php
										}
									?>
									
								</tbody>
								</table>
							</div>
						</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>
