<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/navdean"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<div class="container">
	<h1 class="thin">Dean Dashboard</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row">
			<div class="col s12" style="color: black;">
				<h5><b>Dept: </b>College of ICT</h5>
			</div>
		</div>
		<div class="row ">
			<div class="input-field col s2">
				<select>
					<option value="" disabled>Choose your option</option>
					<option value="1" selected>2017-2018</option>
					<option value="1">2017-2018</option>
					<option value="1">2017-2018</option>
					<option value="1">2017-2018</option>
					<option value="1">2017-2018</option>
				</select>
				<label>School Year</label>
			</div>
			<div class="input-field col s2">
				<select>
					<option value="" disabled>Choose your option</option>
					<option value="1">1st sem</option>
					<option value="2" selected >2nd sem</option>
				</select>
				<label>Semester</label>
			</div>
		</div>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light center" style="color: white;">
								Evaluate Faculty
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							<div class="container">
								<div class="row">
									<div class="col s12">
										<p><b>Evaluation Code:</b> WFR3G2</p>
										<p><b>Faculty ID:</b> 123</p>
										<p><b>Faculty Name:</b> Ramon Alexis Celis</p>
										<p><b>Subject:</b> Comp Prog 1</p>
									</div>
								</div>
								<div class="row">
									<div class="col s12">
										<h5 style="color: #455b65;">Legend:</h5>
									</div>
									<div class="col s12">
										<table class="bordered" style="margin-bottom: 15px;">
											<thead>
												<tr>
													<th>Scale</th>
													<th>Descriptive Rating</th>
													<th>Qualitative Description</th>
												</tr>
											</thead>

											<tbody>
											<tr>
												<td>5</td>
												<td>Outstanding</td>
												<td>
													The performance almost exceeds the job requirements.
													The Faculty is an exceptional role model
												</td>
											</tr>

											<tr>
												<td>4</td>
												<td>Very Satisfactory</td>
												<td>
													The performance meets and often exceeds the job requirements
												</td>
											</tr>

											<tr>
												<td>3</td>
												<td>Satisfactory</td>
												<td>
													The performance meets job requirements
												</td>
											</tr>

											<tr>
												<td>2</td>
												<td>Fair</td>
												<td>
													The performance needs some development to meet job requirements.
												</td>
											</tr>

											<tr>
												<td>1</td>
												<td>Poor</td>
												<td>
													The faculty fails to meet job requirements
												</td>
											</tr>

											</tbody>
										</table>
									</div>
								</div>
								<div class="row">
									<form name="frmEval" id="frmEval" action="" method="POST">
									<div class="col s12">
<style type="text/css">
	.rad {
		display: inline;
		margin-right: 20px;
	}
</style>

										<?php
											$num = 0;
												foreach( Core::getModel("admin/criteria")->get() as $ct ) {
													?>
													<div class="row">
													<h3 style="color: #87a1ad;"><?=$ct->label?></h3>
													<hr>
													<?php

													foreach( Core::getModel("admin/subcriteria")->where("evaluation_criteria_id", $ct->id)->get() as $sct ) {
														
														?>
														<div class="input-field col s12">
															<div class="row">
																<div class="col s7"><span class="thin flow-text"><?=$sct->question?></span></div>							
																<div class="col s5">
																	<div class="rad">
																		<input name="<?=$sct->id?>" type="radio" id="5-sub-<?=$num?>" value="5" class="validate" />
																		<label for="5-sub-<?=$num?>">5</label>
																	</div>
																	<div class="rad">
																		<input name="<?=$sct->id?>" type="radio" id="4-sub-<?=$num?>" value="4" />
																		<label for="4-sub-<?=$num?>">4</label>
																	</div>
																	<div class="rad">
																		<input name="<?=$sct->id?>" type="radio" id="3-sub-<?=$num?>" value="3" />
																		<label for="3-sub-<?=$num?>">3</label>
																	</div>
																	<div class="rad">
																		<input name="<?=$sct->id?>" type="radio" id="2-sub-<?=$num?>" value="2" />
																		<label for="2-sub-<?=$num?>">2</label>
																	</div>
																	<div class="rad">
																		<input name="<?=$sct->id?>" type="radio" id="1-sub-<?=$num?>" value="1" />
																		<label for="1-sub-<?=$num?>">1</label>
																	</div>
																</div>
															</div>
													  	</div>
											
														<?php
														$num++;
													}
													?>
													</div>
													<?php
												}
											?>
									</div>
									
									<div class="input-field col s12">
										<i class="material-icons prefix">mode_edit</i>
										<textarea id="icon_prefix2" class="materialize-textarea" name="comments"></textarea>
										<label for="icon_prefix2">Comments / Suggestion</label>
									</div>

									<div class="col s12 center">
										<input type="submit" name="Submit" class="btn ">
									</div>

								</form>
								</div>
							</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>

<script type="text/javascript">
	$("form#frmEval").submit(function(e){
    var bol_continue = true;
  $("input:radio.validate").each(function(){
    if($(this).attr('disabled') != 'disabled'){
      var my_parent = $(this).closest('.input-field');
      if(!$('[name='+$(this).attr('name')+']').is(':checked')){
        if($(my_parent).children('.warning').length < 1){
          $(my_parent).css("border","solid red 2px");
          $(my_parent).css("padding-top","1px");
          $('label[name='+$(this).attr('name')+']').css('top', '0.1rem');
          // $(my_parent).append('<div class="col m3 s12 warning"><div class="chip" style="background: white; border: #e4e4e4 1px solid;">Please select an option</div></div>');
        }
        bol_continue = false;
      }else{
        if($(my_parent).find('.warning').length > 0){
          $(this).parent().removeAttr("style");
          $('label[name='+$(this).attr('name')+']').removeAttr('style');
          $(my_parent).find('.warning').remove()
        }
      }
    }
  });
  if(!bol_continue){
    e.preventDefault();
    return false;
  }
});
</script>
