<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/navteacher"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<div class="container">
	<h1 class="thin">Dean Dashboard</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row">
			<div class="col s12" style="color: black;">
				<h5><b>Dept: </b>College of ICT</h5>
			</div>
		</div>
		<div class="row ">
			<div class="input-field col s3">
				<input id="evalcode" type="text" name="evalcode" class="validate">
				<label for="evalcode">Code</label>
			</div>
			<div class="input-field col s3">
				<input type="submit" class="btn" name="btnSearch" value="Search">
			</div>
		</div>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light center" style="color: white;">
								Evaluate Peer
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							<div class="container">
								<div class="row">
									<div class="col s12">
										<p><b>Evaluation Code:</b> WFR3G2</p>
									</div>
									<div class="col s4">
										<p><b>Faculty Name: </b>Ramon Alexis Celis</p>
									</div>
									<div class="col s4">
										<p><b>School Year: </b>2017-2018</p>
									</div>
									<div class="col s4">
										<p><b>Semester: </b>2nd</p>
									</div>
									<div class="col s6">
										<p><b>Subject Handled: </b>Computer Programming</p>
									</div>
									<div class="col s6">
										<p><b>College Dept.: </b>ICT</p>
									</div>
								</div>
								<hr>

								<!-- legend block -->
								<?php $this->getChildBlock("admin/legend"); ?>

								<!-- Evaluate form -->
								<?php $this->getChildBlock("admin/evaluate"); ?>
							</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>


