<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/nav"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
</style>
<!-- Main START -->
<main>
	<div class="container ">
		<div class="row ">
			<div class="col s10 ">
				<span>&nbsp</span>
			</div>
			<div class="col s2">
				<ul id="dropdown2" class="dropdown-content pull-right">
					<li>
						<a href="#!">Profile<span class="badge">1</span></a>
					</li>
					<li>
						<a href="#!">Change Password</a>
					</li>
					<li>
						<a href="#!">Change Email</a>
					</li>
				</ul>
				<a class="btn dropdown-button" href="#!" data-activates="dropdown2">Menu<i class="material-icons right">arrow_drop_down</i></a>
			</div>
		</div>
	</div>
<div class="container">
	<h1 class="thin">Admin Dashboard</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light" style="color: white;">
								Tasks
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							<h1 class="center">Working Area</h1>
						</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 