<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/nav"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<div class="container">
	<h1 class="thin">Admin Dashboard</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light" style="color: white;">
								Tasks
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							<div id="chartContainer" style="height: 300px; width: 100%;"></div>
						</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>



	<script type="text/javascript">

window.onload = function () {
	var chart = new CanvasJS.Chart("chartContainer", {
		title:{
			text: "My First Chart in CanvasJS"              
		},
		data: [              
		{
			// Change type to "doughnut", "line", "splineArea", etc.
			type: "column",
			dataPoints: [
				{ label: "apple",  y: 10  },
				{ label: "orange", y: 15  },
				{ label: "banana", y: 25  },
				{ label: "mango",  y: 30  },
				{ label: "grape",  y: 28  }
			]
		}
		]
	});
	chart.render();
}

</script>