<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/nav"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<div class="container">
	<h1 class="thin">Admin Dashboard</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light" style="color: white;">
								Evaulations
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							<div id="chartContainer" style="height: 370px; width: 100%;"></div>
						</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>
<script type="text/javascript">

window.onload = function () {
	var dataPoints = [];
	var chart = new CanvasJS.Chart("chartContainer", {
		animationEnabled: true,
		theme: "light2", // "light1", "light2", "dark1", "dark2"
		
		data: [{        
			dataPoints: dataPoints
		}]
	});

	
	setInterval(function(){
		$.getJSON("<?=Core::getBaseUrl()?>evaluation/api/getAdminData", function(data) {
			dataPoints.length = 0;
			for (var i = 0; i < data.length; i++) {
				dataPoints.push({
					label: data[i].criteria,
					y: data[i].value
				});

			}
			chart.render();
		});
	}, 2000);
}



</script>