
<?php

$session = Core::getSingleton("system/session");
$accountDb = Core::getModel("account/account");
if( $accountDb->isAccountType("Admin") ) {
	$this->getChildBlock("admin/nav");
}

if( $accountDb->isAccountType("Dean") ) {
	$this->getChildBlock("admin/navdean");
}

if( $accountDb->isAccountType("Teacher") ) {
	$this->getChildBlock("admin/navteacher");
}

?>

<?php $this->getChildBlock("page/icon"); ?>
<!-- Main Start -->
<main>
  <div class="container">
	<h1 class="thin">My Account</h1>
	<!--  Tables Section-->
	<div id="messages" class="mailbox section">
	  <div class="row">
	  	<?php $this->getChildBlock("page/alert"); ?>
		<div class="col s12">
		  <div class="z-depth-1">
			<ul class="tabs account">
				<li class="col s4 tab"><a class="active" href="#personal">Profile</a></li>
				<!-- <li class="col s4 tab"><a href="#password">Password</a></li> -->
				<!-- <li class="col s4 tab"><a href="#privacy">Settings</a></li> -->
			</ul>
		  </div>
		</div>
		<div class="col s12">
		  <div class="card-panel no-padding">
			<?php $this->getChildBlock("admin/personal"); ?>
			<?php #$this->getChildBlock("admin/password"); ?>
			<?php #$this->getChildBlock("account/togglsetup"); ?>

		   
		  </div>
		</div>
		<div class="section col s12">
		  <div class="row"> 
			<!--SOCIAL card dark START -->
			<!-- <div class="col s12 m4">
			  <div class="card">
				<div class="card-content center-align">
				  <div class="card-title truncate">Caroline Doe</div>
				  <div class="air-box-6"> <img class="responsive-img circle" src="imgs/operator-female-smile_sml01.jpg"> </div>
				  <p>support</p>
				  <br>
				  <div class="center-align social"> <a href="#" class="circle"><img class="responsive-img" src="imgs/facebook.svg"></a> <a href="#" class="circle"><img class="responsive-img" src="imgs/twitter.svg"></a> <a href="#" class="circle"><img class="responsive-img" src="imgs/gplus.svg"></a> </div>
				</div>
				<div class="card-action center-align truncate"> <a href="#">San Jose, California</a> </div>
			  </div>
			</div> -->
			<!--SOCIAL card END --> 
			<!--SOCIAL card dark START -->
			<!-- <div class="col s12 m4">
			  <div class="card secondary-color">
				<div class="card-content center-align">
				  <div class="card-title primary-color-text truncate">Caroline Doe</div>
				  <div class="air-box-6"> <img class="responsive-img circle" src="imgs/operator-female-smile_sml01.jpg"> </div>
				  <p class="primary-color-text">support</p>
				  <br>
				  <div class="center-align social"> <a href="#" class="circle"><img class="responsive-img" src="imgs/facebook-w.svg"></a> <a href="#" class="circle"><img class="responsive-img" src="imgs/twitter-w.svg"></a> <a href="#" class="circle"><img class="responsive-img" src="imgs/gplus-w.svg"></a> </div>
				</div>
				<div class="card-action center-align truncate"> <a href="#">San Jose, California</a> </div>
			  </div>
			</div> -->
			<!--SOCIAL card dark END --> 
		  </div>
		</div>
	  </div>
	</div>
  </div>
  <!-- container END --> 
  
</main>
<!-- Main END --> 
<script type="text/javascript">
	$("body").removeClass("loading")
</script>