<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/navteacher"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<div class="container">
	<h1 class="thin">Students Rating</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row ">
			<form>
				<div class="input-field col s3">
					<select name="scyear">
						<option value="" disabled selected>Choose your option</option>
						
						<?php
							foreach( Core::getSingleton("evaluation/evaluation")->getSchoolYear() as $scyear ) {
								$selectedScyear = "";
								if( isset($_GET["scyear"]) ) {
									if( $_GET["scyear"] == $scyear ) {
										$selectedScyear = "selected";
									}
								}
								?>
								<option value="<?=$scyear?>" <?=$selectedScyear?>><?=$scyear?></option>
								<?php
							}
						?>
					</select>
					<label>School Year</label>
				</div>
				<div class="input-field col s3">
					<select name="sem">
						<option value="" disabled selected>Choose your option</option>
						<?php
							foreach( Core::getSingleton("evaluation/evaluation")->getSemester() as $sem ) {
								$selectedSem = "";
								if( isset($_GET["sem"]) ) {
									if( $_GET["sem"] == $sem ) {
										$selectedSem = "selected";
									}
								}
								?>
								<option value="<?=$sem?>" <?=$selectedSem?>><?=$sem?></option>
								<?php
							}
						?>
					</select>
					<label>Semester</label>
				</div>
				<div class="input-field col s3">
					<input type="submit" class="btn" name="btnView" value="View">
				</div>
			</form>
		</div>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light center" style="color: white;">
								Ratings
							</h5>
						</div>
						<div id="tasks">
							<div class="row">
									<table class="highlight centered" style="margin-bottom: 15px;">
										<thead>
											<tr>
												<th>Name</th>
												<th>Course and Year</th>
												<th>Rating</th>
												<th>Action</th>
											</tr>
										</thead>

										<tbody>
										<?php
											$request 			= Core::getSingleton("url/request")->getRequest();
											$session 			= Core::getSingleton("system/session");
											$auth 				= $session->get("auth");
											$accountDb 			= Core::getModel("account/account");
											$evaluationDb 		= Core::getModel("evaluation/evaluation");
											$evaluationDetailsDb = Core::getModel("evaluation/evaluationdetails");
											$evaluatorDb 		= Core::getModel("evaluation/evaluator");
											$ratingDb 			= Core::getModel("evaluation/rating");
											$scyear 			= Core::getSingleton("evaluation/evaluation")->getSchoolYear()[0];
											$sem 				= Core::getSingleton("evaluation/evaluation")->getSemester()[0];

											if( isset($request["scyear"]) ) {
												$scyear = $request["scyear"];
											}

											if( isset($request["sem"]) ) {
												$sem = $request["sem"];
											}

											$evaluation = $evaluationDb->where("account_id", $auth->id)->first();
											if(! $evaluation ) { $this->getChildBlock("page/noeval"); return;}
											$evaluationDetails = $evaluationDetailsDb
												->where("school_year", $scyear)
												->where("semester", $sem)
												->where("evaluation_id", $evaluation->id)
												->get();

											$sumRating = 0;
											$noOfItems = 0;
											foreach( $evaluationDetails as $ed ) {
												$evaluator = $evaluatorDb
													->where("id", $ed->evaluator_id)
													->where("type", "Student")
													->first();

												$rating = $ratingDb->where("id", $ed->rating_id)->first();

												if(! $evaluator ) {
													continue;
												}
												$sumRating = $sumRating + $rating->ave_total;
												$noOfItems++;
												?>
												<tr>
													<td><?=$evaluator->name?></td>
													<td><?=$evaluator->course?></td>
													<td><?=$rating->ave_total?></td>
													<td><a class="modal-trigger" href="#modal<?=$ed->id?>">View Comment</a></td>
												</tr>
													<!-- Modal Structure -->
													  <div id="modal<?=$ed->id?>" class="modal">
													    <div class="modal-content">
													      <h4 class="thin" style="color: #87a1ad;"><?=$evaluator->name?>'s Comment</h4>
													      <p><?=$ed->comments?></p>
													    </div>
													    <div class="modal-footer">
													      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
													    </div>
													  </div>
													<!-- Main END --> 
												<?php
											}

										?>
										
										</tbody>
									</table>
								</div>

								<div class="row">
									<div class="col s2 offset-s9">
										<?php
										$ave = 0;
										if( $noOfItems ) {	$ave = ($sumRating / $noOfItems); }
										?>
										<p><b>Average Rating:</b> <?=$ave?></p>
									</div>
								</div>
						</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>

  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4 class="thin" style="color: #87a1ad;">Angelou Macabutas's Comment</h4>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
  </div>
<!-- Main END --> 
