<?php $this->getChildBlock("page/preloader"); ?>
<?php 
$session = Core::getSingleton("system/session");
$accountDb = Core::getModel("account/account");
$accountType = $accountDb->getAccountType($session->get("auth")->id);

if( $accountDb->isAccountType("Admin") ) {
	$this->getChildBlock("admin/nav");
}

if( $accountDb->isAccountType("Dean") ) {
	$this->getChildBlock("admin/navdean");
}

if( $accountDb->isAccountType("Teacher") ) {
	$this->getChildBlock("admin/navteacher");
}

?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<div class="container">
	<h1 class="thin">Dean Dashboard</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row">
			<div class="col s12" style="color: black;">
				<h5><b>Dept: </b><?=Core::getModel("account/account")->getDepartment($_SESSION["auth"]->id)->label;?></h5>
			</div>
		</div>
		<div class="row ">
		
		</div>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light center" style="color: white;">
								List Of Self Evaluated Faculty 
							</h5>
						</div>
						<div id="tasks">
							<div class="container">
								<table style="margin: 15px;" class="highlight centered">
								<thead>
								  <tr>
									  <th>Faculty Name</th>
									  <th>Academic Rank</th>
									  <th>School Year</th>
									  <th>Sem</th>
									  <th>Status</th>
									  <th>Action</th>
								  </tr>
								</thead>

									<tbody>
										<?php 
											$selfEvaluationDb = Core::getModel("evaluation/evaluationself");
											$teachers = $selfEvaluationDb->getDeansTeachers();
											foreach( $teachers as $teacher ) {
												if(! $selfEvaluationDb->hasEvaluated( $teacher->id ) ) {
													continue;
												}
												$eval = $selfEvaluationDb->where("account_id", $teacher->id)->first();
												?>
													<tr>
														<td><?=$teacher->fname?> <?=$teacher->lname?></td>
														<td><?=Core::getModel("account/accounttype")->getAccountType($teacher->account_type_id)->type?></td>
														<td><?= $eval->scyear ?></td>
														<td><?= $eval->sem ?></td>
														<td><?= $eval->status ?></td>
														<td>
															<?php
																if( Core::getModel("evaluation/evaluationself")::STATUS_PENDING === $eval->status ) {
																	?>
																	<a href="<?=Core::getBaseUrl()?>admin/faculty/approveSelfEvaluation/id/<?=$teacher->id?>">Approve</a>
																	<?php
																}else{
																	?>
																	<a href="<?=Core::getBaseUrl()?>admin/faculty/disapproveSelfEvaluation/id/<?=$teacher->id?>" style="color: red;">Disapprove</a>
																	<?php
																}
															?>
														</td>
													</tr>
												<?php
											}
										?>
									</tbody>
								</table>
							</div>
						</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>
