<?php
	$accountDb = Core::getModel("account/account");
	$session = Core::getSingleton("system/session");
	if(! $accountDb->isTeacher() ) {
		$session->add("alert", [
			"type" => "error",
			"message" => "This is for teacher evaluation only."
		]);
		$this->_redirect(Core::getBaseUrl() . "admin");
	}
?>

<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/navteacher"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<div class="container">
	<h1 class="thin"> Self Evaluation </h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row">
			<div class="col s12" style="color: black;">
				<h5><b>Dept: </b><?=Core::getModel("account/account")->getDepartment($_SESSION["auth"]->id)->label;?></h5>
			</div>
		</div>
		<!-- <div class="row ">
			<form name="frmSearchCode" action="<?=Core::getBaseUrl()?>admin/evaluation/validateCode" method="POST">
				<div class="input-field col s3">
					<input id="evalcode" type="text" name="evalcode" class="validate">
					<label for="evalcode">Code</label>
				</div>
				<div class="input-field col s3">
					<input type="submit" class="btn" name="btnSearch" value="Search">
				</div>
			</form>
		</div> -->
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light center" style="color: white;">
								Evaluate Peer
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							<?php
								// dont let the teacher take evaluation without code
								$evalCode = Core::getModel("evaluation/evaluation")
									->where("account_id", Core::getSingleton("system/session")->get("auth")->id)
									->first();
									// Core::log(  );
								if(! empty($evalCode) ) {
									$_SESSION["evaluation"]["access"] = true;
									$_SESSION["evaluation"]["code"] = $evalCode->code;
									$_SESSION["evaluation"]["hasEvaluator"] = true;
								}
								
								if( isset($_SESSION["evaluation"]) ) {
									$evaluationDb = Core::getModel("admin/evaluation");
									$accountDb = Core::getModel("account/account");
									$account = $evaluationDb->getAccountEvaluated( $_SESSION["evaluation"]["code"] );
									$accountData = $accountDb->getAccountData( $account->id );
									?>
									<div class="container">
										<div class="row">
											<div class="col s12">
												<p><b>Evaluation Code:</b> Self Evaluation</p>
											</div>
											<div class="col s4">
												<p><b>Faculty Name: </b><?=$account->fname?> <?=$account->lname?></p>
											</div>
											<div class="col s4">
												<p><b>School Year: </b><?=$accountData->scyear?></p>
											</div>
											<div class="col s4">
												<p><b>Semester: </b><?=$accountData->sem?></p>
											</div>
											<div class="col s6">
												<p><b>Subject Handled: </b><?=Core::getModel("admin/subject")->where("id", $accountData->subject_id)->first()->subject_title?></p>
											</div>
											<div class="col s6">
												<p><b>College Dept.: </b><?=$accountDb->getDepartment($account->id)->label?></p>
											</div>
										</div>
										<hr>

										<?php
											if( Core::getModel("evaluation/evaluationself")->hasEvaluated() ) {
												?>
												<div class="row">
											      <div class="col s12 m12">
											        <div class="card-panel center" style="background-color: #455b65; color: white;">
											          <span>Your Account is not eledgible for self evaluation.</span>
											        </div>
											      </div>
											    </div>
												<?php
											}else{
												// <!-- legend block -->
												$this->getChildBlock("admin/legend");
												// <!-- Evaluate form -->
												$this->getChildBlock("evaluation/questions", ["action" => Core::getBaseUrl() . "admin/evaluation/submitSelfEvaluation" ]);
											}
										?>
	
										
									
									</div>
									<?php
								}else{
									?>
										<div class="col s12 centered">
										    <div class="card horizontal">
										      <div class="card-stacked">
										        <div class="card-content">
										          <p class="center">This account is not up for evaluation</p>
										        </div>
										      </div>
										    </div>
										  </div>
									<?php
								}
							?>
					</ul
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>



