<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/navteacher"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}

	.canvasjs-chart-credit {
	   display: none;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<div class="container">
	<h1 class="thin">Faculty Dashboard</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row">
			<form name="frmView">
				<div class="col s12">
					<div class="input-field col s3">
						<select name="scyear">
							<option value="" disabled>Choose your option</option>
							
							<?php
								foreach( Core::getSingleton("evaluation/evaluation")->getSchoolYear() as $scyear ) {
									?>
									<option value="<?=$scyear?>"><?=$scyear?></option>
									<?php
								}
							?>
						</select>
						<label>School Year</label>
					</div>
					<div class="input-field col s3">
						<select name="sem">
							<option value="" disabled>Choose your option</option>
							
							<?php
								foreach( Core::getSingleton("evaluation/evaluation")->getSemester() as $sem ) {
									?>
									<option value="<?=$sem?>"><?=$sem?></option>
									<?php
								}
							?>
						</select>
						<label>Semester</label>
					</div>
					<div class="input-field col s3">
						<input type="submit" value="View" class="btn">
					</div>
				</div>
			</form>
		</div>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light" style="color: white;">
								Information
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							<div id="chartContainer" style="height: 300px; width: 100%;"></div>
						</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>
<?php
$scyear = isset($_GET["scyear"]) ? $_GET["scyear"] : Core::getSingleton("evaluation/evaluation")->getSchoolYear()[0];
$sem = isset($_GET["sem"]) ? $_GET["sem"] : Core::getSingleton("evaluation/evaluation")->getSemester()[0];
$faculty = Core::getSingleton("admin/faculty")->getFacultyData($_SESSION["auth"]->id, $scyear, $sem);
?>

	<script type="text/javascript">

window.onload = function () {
	var chart = new CanvasJS.Chart("chartContainer", {
		title:{
			text: "Recent Evaluation"              
		},
		data: [              
		{
			// Change type to "doughnut", "line", "splineArea", etc.
			type: "column",
			dataPoints: [
				{ label: "Commitment",  y: <?=$faculty['cr1']?>  },
				{ label: "Knowledge of Subject Matter", y: <?=$faculty['cr2']?>  },
				{ label: "Teaching for Independent Learning", y: <?=$faculty['cr3']?>  },
				{ label: "Management of Learning",  y: <?=$faculty['cr4']?>  }
			]
		}
		]
	});
	chart.render();
}

</script>