<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("admin/navdean"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<style type="text/css">
	.bx {
		border: 1px solid red;
	}
	.dropdown-content {
	   overflow-y: visible;
	}

	.dropdown-content .dropdown-content {
	   margin-left: 100%;
	}
</style>
<!-- Main START -->
<main>
<?php $this->getChildBlock("admin/profilemenu"); ?>
<?php
	$request = Core::getSingleton("url/request")->getRequest();
	$accountDb = Core::getModel("account/account");
	$account = $accountDb->where("id", $request["id"])->first();

	if(! $account ) {
		$this->_redirect(Core::getBaseUrl() . "admin/faculty");
	}
	// Form DATA
?>
<div class="container">
	<h1 class="thin">Dean Dashboard</h1>
	<div id="dashboard">
		<form id="frmRegister" class="login-form" action="<?=Core::getBaseUrl()?>admin/faculty/submitUpdate" method="POST">
			<input type="hidden" name="accountId" value="<?=$request["id"]?>">
			<input type="hidden" name="department" value="<?=Core::getModel("account/account")->getDepartment($_SESSION["auth"]->id)->id;?>">
		<?php $this->getChildBlock("page/alert"); ?>
		<div class="row">
			<div class="col s12">
				<div class="input-field col s3">
					<select name="scyear" id="scyear" class="validate" required>
						<option value="" disabled selected>Choose your option</option>
						<?php
							foreach( Core::getSingleton("admin/evaluation")->getSchoolYear() as $sy ) {
								$selected = "";
								if( $accountDb->getAccountData($request["id"])->scyear == $sy ) {
									$selected = "selected";
								}
								?>
								<option value="<?=$sy?>" <?=$selected?>><?=$sy?></option>
								<?php
							}
						?>
					</select>
					<label>School Year</label>
				</div>
				<div class="input-field col s3">
					<select name="sem" id="sem" class="validate" required>
						<option value="" disabled selected>Choose your option</option>
						<?php
							foreach( Core::getSingleton("admin/evaluation")->getSemester() as $sem ) {
								$selected = "";
								if( $accountDb->getAccountData( $request["id"] )->sem == $sem ) {
									$selected = "selected";
								}
								?>
								<option value="<?=$sem?>" <?=$selected?>><?=$sem?></option>
								<?php
							}
						?>
					</select>
					<label>Semester</label>
				</div>
			</div>
		</div>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card ">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light" style="color: white;">
								Create Faculty Account
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							
							<!--  Tables Section-->
						<div class="container">
							<div id="login" class="row">
	  <!-- <h1 class="thin">Login</h1> -->
	  
		<input type="hidden" name="redirect" value="<?=Core::getBaseUrl()?>admin/faculty">
		<!-- <input type="hidden" name="scyear">
		<input type="hidden" name="sem"> -->
		<div class="form-body">
	<?php $this->getChildBlock("page/alert"); ?>
		<div class="row">
	        <div class="input-field col s6">
	        <i class="material-icons prefix">account_circle</i>
	          <input  id="fname" name="fname" type="text" class="validate" value="<?=$account->fname?>">
	          <label for="fname">First Name</label>
	        </div>
	        <div class="input-field col s6">
	        <i class="material-icons prefix">account_circle</i>
	          <input id="lname" name="lname" type="text" class="validate" value="<?=$account->lname?>">
	          <label for="lname">Last Name</label>
	        </div>
	      </div>
		<div class="row">
		  <div class="input-field col s6">
			<i class="mdi-social-person prefix"></i>
			<input id="username" name="username" type="text" class="validate" value="<?=$account->username?>">
			<label for="username" class="center-align">Username</label>
		  </div>
		  <div class="input-field col s6">
			<i class="mdi-communication-email prefix"></i>
			<input id="email" name="email" type="email" class="validate" value="<?=$account->email?>">
			<label for="email" class="center-align">Email</label>
		  </div>
		</div>
		<div class="row">
		  <div class="input-field col s6">
			<i class="mdi-action-lock prefix"></i>
			<input id="password" name="password" type="password" class="validate">
			<label for="password">Password</label>
		  </div>
		  <div class="input-field col s6">
			<i class="mdi-action-lock prefix"></i>
			<input id="repassword" name="repassword" type="password">
			<label for="repassword">Re-type password</label>
		  </div>
		</div>

		<div class="row">
		  <div class="input-field col s6">
				<select name="subject" id="subject" class="validate" required>
					<option value="" disabled selected>Choose your option</option>
					<?php 
						foreach( Core::getModel("admin/subject")->get() as $subject ) {
							$selected = "";
							if( $accountDb->getSubject($request["id"])->id == $subject->id ) {
								$selected = "selected";
							}
							?>
							<option value="<?=$subject->id?>" <?=$selected?>><?=$subject->subject_title?></option>
							<?php
						}
					?>
					
				</select>
				<label>Subject</label>
			</div>
		</div>
		
		<div class="row">
		  <div class="input-field col s12">
			<input type="submit" href="<?=Core::getBaseUrl()?>account/register/create" class="btn-large waves-effect waves-light col s12" value="Update">
		  </div>
		</div>
	  </div>
	  
  </div>
						</div>


						</div>
					</ul>
				</div>
			</div>
		</div>
		</form>
	</div>
</div>
</main>
<!-- Main END --> 

<?php $this->getChildBlock("page/footer"); ?>

<script type="text/javascript">
  $("#frmRegister").validate({
		rules: {
			username: {
				required: true,
				minlength: 5
			},
			fname: {
				required: true,
			},
			lname: {
				required: true,
			},
			sem: {
				required: true,
			},
			scyear: {
				required: true,
			},
			email: {
				required: true,
				email:true
			},
		// 	password: {
		// required: true,
		// minlength: 5
	 //  },
	 //  repassword: {
		// required: true,
		// minlength: 5,
		// equalTo: "#password"
	 //  },
			
		//For custom messages
		messages: {
			uname:{
				required: "Enter a username",
				minlength: "Enter at least 5 characters"
			},
			curl: "Enter your website",
		},
		errorElement : 'div',
		errorPlacement: function(error, element) {
		  var placement = $(element).data('error');
		  if (placement) {
			$(placement).append(error)
		  } else {
			error.insertAfter(element);
		  }
		}
	 });
</script>