<form method="POST" action="">
	<div class="input-field col s5">
		<input id="last_name" type="text" class="validate">
		<label for="last_name">Username</label>
	</div>
	<div class="input-field col s5">
		<input id="password" type="password" class="validate">
     	<label for="password">Password</label>
	</div>
	<div class="input-field col s2">
		<button class="btn waves-effect waves-light" type="submit" name="action">
			Login
			<i class="material-icons right">send</i>
		</button>
	</div>
</form>