#!/usr/bin/env php
<?php
/**
 *	Require lexi core file
 */
require_once "app/Core.php";

/**
 *	CLI
 */
$interface = Core::getSingleton("console/interface");
$interface->setArgs( $argv );
$interface->run();