<?php $this->getChildBlock("page/nav"); ?>

<div class="wrapper wrapper-full-page">
        <div class="full-page pricing-page" data-image="../../assets/img/bg-pricing.jpg">
            <div class="content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 text-center">
                            <h1 class="title">LexiPHP</h1>
                            <h5 class="description">This is a lightweight PHP framework made to simplify and organize your with MVC Pattern</h5>
                        </div>
                    </div>
                </div>
            </div>
            <?php $this->getChildBlock("page/footer"); ?>
        </div>
    </div>