<?php
$exception = $this->errors;
if( count($exception->getTrace()) < 1 ) {
	return;
}
// echo "<pre>";
// print_r($this->errors);
// echo "</pre>";
?>

<h2>Traces</h2>
<div class="container" style="overflow-y: auto; height: 350px;">
	<?php
		foreach( $exception->getTrace() as $traces ) {
			echo "<pre>";
			foreach( $traces as $key => $val ) {
				if( is_array($val) ) {
					foreach( $val as $trc ) {
						if( is_array($trc) ) {
							echo "\n";
							print_r($trc);
						}else{
							echo "\n" . $trc;
						}						
					}
					echo "<hr>";
				}else{
					?>
					<?="\n"?><?=$key?>: <?=$val?> 
					<?php
				}
			}
			echo "</pre>";
		}
	?>
</div>