<?php
$user = Core::getSingleton("system/session")->get("auth");

?>
<style type="text/css">
	.divider {
		margin-bottom: 10px;
	}
</style>
<div id="privacy">
	<form name="frmUpdateAccount" method="POST" action="<?=Core::getBaseUrl()?>settings/account/update" >
		<div class="form-pad">
			<div class="row">
				<div class="col s12">
					<div class="row" style="margin-top: 20px;">
						<h3>Account</h3>
						<div class="divider"></div>
						 <div class="col s12 m6">
						 	<div class="input-field">
								<input id="apikey" name="apiKey" type="text" class="validate" value="<?=$user->apiKey?>">
								<label for="apikey">API Key</label>
							</div>
						 </div>
						 <div class="col s12 m6">
						 	<div class="input-field">
								<input id="rate" name="rate" type="text" class="validate" value="<?=$user->rate?>">
								<label for="rate">Rate</label>
							</div>
						</div>
						<div class="col s12 m6">
						 	<div class="input-field">
								<input id="targethrs" name="targetHrs" type="number" min="4" max="12" class="validate" value="<?=$user->targetHrs?>">
								<label for="targethrs">Target hours per day</label>
							</div>
						</div>
					</div>

					<div class="row" style="margin-top: 20px;">
						<h3>Deductions</h3>
						<div class="divider"></div>
						 <div class="col s12 m6">
						 	<div class="input-field">
								<input id="sss" name="sss" type="text" class="validate" value="<?=$user->sss?>">
								<label for="sss">SSS</label>
							</div>
						 </div>
						 <div class="col s12 m6">
						 	<div class="input-field">
								<input id="philhealth" name="philhealth" type="text" class="validate" value="<?=$user->philhealth?>">
								<label for="philhealth">PhilHealth</label>
							</div>
						 </div>
						 <div class="col s12 m6">
						 	<div class="input-field">
								<input id="hdmf" name="hdmf" type="text" class="validate" value="<?=$user->hdmf?>">
								<label for="hdmf">HDMF</label>
							</div>
						 </div>
						 <div class="col s12 m6">
						 	<div class="input-field">
								<input id="withholding" name="withholding" type="text" class="validate" value="<?=$user->withholding?>">
								<label for="withholding">Withholding</label>
							</div>
						 </div>
					</div>

					<div class="row" style="margin-top: 20px;">
						<h3>Allowance</h3>
						<div class="divider"></div>
						 <div class="col s12 m12">
						 	<div class="input-field">
								<input id="allowance" name="allowance" type="text" class="validate" value="<?=$user->allowance?>">
								<label for="allowance">Allowance</label>
							</div>
						 </div>
					</div>

					
					<div class="buttons" style="margin-top: 20px;">
						<button class="waves-effect waves-light btn" type="submit" name="btnUpdateSettings"><i class="material-icons right">done</i>Save changes</button>
						<button class="waves-effect waves-light btn blue-grey lighten-2" type="submit" name="action2"><i class="material-icons right">clear</i>Cancel</button>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>

<?php
	$toggl = Core::getSingleton("toggl/handler");
	if(! $toggl->isSetup() ) {
?>
<script type="text/javascript">
	var $toastContent = $('<span>Hey! <a href="<?=Core::getBaseUrl()?>/toggl/handler/goSetup"> Sync </a> now.</span>').add($('<button class="btn-flat toast-action">Undo</button>'));
	Materialize.toast($toastContent, 10000);
</script>
<?php
	}
?>