<div class="container">

      <h1><?= $this->getType() ?></h1>

      <p>
        <?= $this->getMessage() ?>
      </p>

      <p>
        <a href="https://github.com/MashiruAlexis/LexiPHP/tree/1.0.4">Read the full documentation</a>
        for more information about using <strong>LexiPHP</strong>.
      </p>

      <div id="suggestions">
        <a href="https://github.com/MashiruAlexis/LexiPHP">GitHub Status</a> &mdash;
        <a href="https://github.com/MashiruAlexis/LexiPHP">@LexiPHP</a>
      </div>
    </div>