<div class="container">

      <h1><?= $this->getType() ?></h1>
      <p><strong>File not found</strong></p>

      <p>
        The site configured at this address does not
        contain the requested file.
      </p>

      <p>
        <?= $this->getMessage() ?>
      </p>

      <p>
        <a href="<?= $this->getLink() ?>">Read the full documentation</a>
        for more information about using <strong>GitHub Pages</strong>.
      </p>

      <div id="suggestions">
        <a href="https://github.com/MashiruAlexis/LexiPHP">GitHub Status</a> &mdash;
        <a href="https://github.com/MashiruAlexis/LexiPHP">@LexiPHP</a>
      </div>
    </div>