<?php $this->getChildBlock("page/navmember"); ?>
<?php $this->getChildBlock("page/icon"); ?>
<!-- Main Start -->
<main>
  <div class="container">
	<h1 class="thin">My Account</h1>
	<!--  Tables Section-->
	<div id="messages" class="mailbox section">
	  <div class="row">
		<div class="col s12">
		  <div class="z-depth-1">
			<ul class="tabs account">
				<!-- <li class="col s4 tab"><a class="active" href="#personal">Profile</a></li> -->
				<!-- <li class="col s4 tab"><a href="#password">Password</a></li> -->
				<li class="col s4 tab"><a href="#privacy">Settings</a></li>
			</ul>
		  </div>
		</div>
		<div class="col s12">
		  <div class="card-panel no-padding">
		  	<?php $this->getChildBlock("page/alert"); ?>
			<?php $this->getChildBlock("settings/settings"); ?>
		  </div>
		</div>
	  </div>
	</div>
  </div>
  <!-- container END --> 
  
</main>
<!-- Main END --> 
<script type="text/javascript">
	$("body").removeClass("loading")
</script>