<div class="row">
	<div class="col s12">
		<span class="flow-text">This div is 12-columns wide on all screen sizes</span>
		<h4 class="truncate">This is an extremely long title that will be truncated</h4>
		<div class="card-panel hoverable red darken-3"> Hoverable Card Panel</div>
	</div>
</div>

<section class="sect">
	<div class="card-panel hoverable red darken-3"> Hoverable Card Panel</div>
</section>