<?php $this->getChildBlock('pages/nav'); ?>
<?php $this->getChildBlock('sales/checkboxstyle'); ?>
<div class="container-fluid" style="margin-top: 15px;">
	<h3 style="margin-left: 15px;">WEB ADVERTISING BOOKING CONTRACT</h3>
	<div class="row">

		<div class="col-md-8">
			<form>
				<!-- name -->
			  <div class="form-group row">
			    <label for="name" class="col-sm-3 col-form-label">Name: Mr. /M/S</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="name" required>
			    </div>
			  </div>

			  <!-- company -->
			  <div class="form-group row">
			    <label for="company" class="col-sm-3 col-form-label">Company</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="company" required>
			    </div>
			  </div>

			  <!-- phone -->
			  <div class="form-group row">
			    <label for="phone" class="col-sm-3 col-form-label">Phone</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="phone" required>
			    </div>
			  </div>

			  <!-- email -->
			  <div class="form-group row">
			    <label for="email" class="col-sm-3 col-form-label">Email</label>
			    <div class="col-sm-8">
			      <input type="email" class="form-control" id="email" required>
			    </div>
			  </div>

			</form>
		</div>
		<div class="col-md-2">
			<!-- No. -->
			  <div class="form-group row">
			    <label for="num" class="col-sm-3 col-form-label">No.</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="num" required>
			    </div>
			  </div>
		</div>
	</div>

	<div class="row" style="margin-top: 15px;">
		<div class="col-md-6">
			<h3>ADVERTISEMENT TARIFF PLAN</h3>
			<p>
				Top Left (Main Page)
				<label class="checkbox">
                 	<input type="checkbox" />
                	<span class="default"></span>
                 </label>
			</p>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Tariff</th>
						<th scope="col">1 Week</th>
						<th scope="col">2 Weeks</th>
						<th scope="col">1 Month</th>
						<th scope="col">3 Months</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">A</th>
						<td>
							1000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							1800
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							3000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							7500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
				</tbody>
			</table>

			<p>
				Body (Main Page)
				<label class="checkbox">
                 	<input type="checkbox" />
                	<span class="default"></span>
                 </label>
			</p>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Tariff</th>
						<th scope="col">1 Week</th>
						<th scope="col">2 Weeks</th>
						<th scope="col">1 Month</th>
						<th scope="col">3 Months</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">B</th>
						<td>
							450
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							800
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							1500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							3500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
				</tbody>
			</table>

			<p>
				Inside News Page
				<label class="checkbox">
                 	<input type="checkbox" />
                	<span class="default"></span>
                 </label>
			</p>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Tariff</th>
						<th scope="col">1 Week</th>
						<th scope="col">2 Weeks</th>
						<th scope="col">1 Month</th>
						<th scope="col">3 Months</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">C</th>
						<td>
							1500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							2400
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							4000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							9500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
				</tbody>
			</table>

			<p>
				All above advertising
				<label class="checkbox">
                 	<input type="checkbox" />
                	<span class="default"></span>
                 </label>
			</p>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Tariff</th>
						<th scope="col">1 Week</th>
						<th scope="col">2 Weeks</th>
						<th scope="col">1 Month</th>
						<th scope="col">3 Months</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">D</th>
						<td>
							1500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							2700
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							5000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							1300
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
				</tbody>
			</table>

			<p>
				Pop-Up (Flash/Picture)
				<label class="checkbox">
                 	<input type="checkbox" />
                	<span class="default"></span>
                 </label>
			</p>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Tariff</th>
						<th scope="col">1 Week</th>
						<th scope="col">2 Weeks</th>
						<th scope="col">1 Month</th>
						<th scope="col">3 Months</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">A</th>
						<td>
							2000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							3300
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							6000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							14000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="col-md-6">
			<h3 style="float: right;">SOCIAL MEDIA TARIFF PLAN</h3>
		</div>
	</div>
</div>