<?php $this->getChildBlock('pages/nav'); ?>
<?php $this->getChildBlock('sales/checkboxstyle'); ?>
<div class="container-fluid" style="margin-top: 15px;">
	<h3 style="margin-left: 15px;">WEB ADVERTISING BOOKING CONTRACT</h3>
	<div class="row">
		<div class="col-md-8">
			<form>
				<!-- name -->
			  <div class="form-group row">
			    <label for="name" class="col-sm-3 col-form-label">Name: Mr. /M/S</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="name" required>
			    </div>
			  </div>

			  <!-- company -->
			  <div class="form-group row">
			    <label for="company" class="col-sm-3 col-form-label">Company</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="company" required>
			    </div>
			  </div>

			  <!-- phone -->
			  <div class="form-group row">
			    <label for="phone" class="col-sm-3 col-form-label">Phone</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="phone" required>
			    </div>
			  </div>

			  <!-- email -->
			  <div class="form-group row">
			    <label for="email" class="col-sm-3 col-form-label">Email</label>
			    <div class="col-sm-8">
			      <input type="email" class="form-control" id="email" required>
			    </div>
			  </div>

			</form>
		</div>
		<div class="col-md-2">
			<!-- No. -->
			  <div class="form-group row">
			    <label for="num" class="col-sm-3 col-form-label">No.</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="num" required>
			    </div>
			  </div>
		</div>
	</div>

	<div class="row" style="margin-top: 15px;">
		<div class="col-md-6">
			<h3>ADVERTISEMENT TARIFF PLAN</h3>
			<p>
				Top Left (Main Page)
				<label class="checkbox">
                 	<input type="checkbox" />
                	<span class="default"></span>
                 </label>
			</p>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Tariff</th>
						<th scope="col">1 Week</th>
						<th scope="col">2 Weeks</th>
						<th scope="col">1 Month</th>
						<th scope="col">3 Months</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">A</th>
						<td>
							1000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							1800
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							3000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							7500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
				</tbody>
			</table>

			<p>
				Body (Main Page)
				<label class="checkbox">
                 	<input type="checkbox" />
                	<span class="default"></span>
                 </label>
			</p>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Tariff</th>
						<th scope="col">1 Week</th>
						<th scope="col">2 Weeks</th>
						<th scope="col">1 Month</th>
						<th scope="col">3 Months</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">B</th>
						<td>
							450
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							800
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							1500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							3500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
				</tbody>
			</table>

			<p>
				Inside News Page
				<label class="checkbox">
                 	<input type="checkbox" />
                	<span class="default"></span>
                 </label>
			</p>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Tariff</th>
						<th scope="col">1 Week</th>
						<th scope="col">2 Weeks</th>
						<th scope="col">1 Month</th>
						<th scope="col">3 Months</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">C</th>
						<td>
							1500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							2400
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							4000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							9500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
				</tbody>
			</table>

			<p>
				All above advertising
				<label class="checkbox">
                 	<input type="checkbox" />
                	<span class="default"></span>
                 </label>
			</p>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Tariff</th>
						<th scope="col">1 Week</th>
						<th scope="col">2 Weeks</th>
						<th scope="col">1 Month</th>
						<th scope="col">3 Months</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">D</th>
						<td>
							1500
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							2700
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							5000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							1300
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
				</tbody>
			</table>

			<p>
				Pop-Up (Flash/Picture)
				<label class="checkbox">
                 	<input type="checkbox" />
                	<span class="default"></span>
                 </label>
			</p>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Tariff</th>
						<th scope="col">1 Week</th>
						<th scope="col">2 Weeks</th>
						<th scope="col">1 Month</th>
						<th scope="col">3 Months</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">A</th>
						<td>
							2000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							3300
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							6000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							14000
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
				</tbody>
			</table>

			<h3>Advertisement Tariff</h3>
			<div class="col-md-12" style="padding: 20px; background-color: #ffa50057;">
				<div class="form-group row">
					<label for="adtarrif" class="col-sm-6 col-form-label">Advertisement TARIFF</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="adtarrif">
					</div>
				</div>
				<div class="form-group row">
					<label for="withHomePage" class="col-sm-6 col-form-label">With Home Page(extra 10%)</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="withHomePage">
					</div>
				</div>
				<div class="form-group row">
					<label for="designatedPage" class="col-sm-6 col-form-label">Designated Page(extra 10%)</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="designatedPage">
					</div>
				</div>
				<div class="form-group row">
					<label for="desPrice" class="col-sm-6 col-form-label">Design Price</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="desPrice">
					</div>
				</div>
				<div class="form-group row">
					<label for="vat" class="col-sm-6 col-form-label">VAT (5%)</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="vat">
					</div>
				</div>
				<div class="form-group row">
					<label for="addTariffTotal" class="col-sm-6 col-form-label">Total</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="addTariffTotal">
					</div>
				</div>
			</div>
			<div class="col-md-12" style="margin-top: 1%;padding: 15px 15px 1px 15px; background-color: #00800054;">
				<div class="form-group row">
					<label for="addTariffTotal" class="col-md-4 col-form-label">Campaign start from:</label>
					<div class="col">
						<input type="text" class="form-control" id="addTariffTotal">
					</div>
					<label for="addTariffTotal" class="col-md-2 col-form-label">end:</label>
					<div class="col-md-4">
						<input type="text" class="form-control" id="addTariffTotal">
					</div>
				</div>
			</div>

		</div>
		<div class="col-md-6">
			<h3>SOCIAL MEDIA TARIFF PLAN</h3>
			<table class="table">
				<thead>
					<tr>
						<th scope="col" colspan="5">COVER OF THE MAGAZINE</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							1 WEEK
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							2 WEEKS
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							3 WEEKS
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							1 MONTH
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
					<tr>
						<td>1250</td>
						<td>2200</td>
						<td>3000</td>
						<td>3850</td>
					</tr>
				</tbody>
			</table>

			<table class="table">
				<thead>
					<tr>
						<th scope="col" colspan="5">INSTAGRAM</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							1 WEEK
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							2 WEEKS
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							3 WEEKS
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							1 MONTH
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
					<tr>
						<td>750 AED<br/>21 POSTS</td>
						<td>1250 AED<br/>42 POSTS</td>
						<td>1750 AED<br/>63 POSTS</td>
						<td>2300 AED<br/>84 POSTS</td>
					</tr>
				</tbody>
			</table>

			<table class="table">
				<thead>
					<tr>
						<th scope="col" colspan="5">YOUTUBE(1) LOGO ON THE RIGTH (30 SECONDS FOREVER)</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							A
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							B
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							C
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
					<tr>
						<td>750</td>
						<td>500</td>
						<td>300</td>
					</tr>
				</tbody>
			</table>

			<table class="table">
				<thead>
					<tr>
						<th scope="col" colspan="5">INSTAGRAM</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							A
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							B
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
                         <td>
							C
							<label class="checkbox">
                             	<input type="checkbox" />
                            	<span class="default"></span>
                             </label>
                         </td>
					</tr>
					<tr>
						<td>1200</td>
						<td>600</td>
						<td>350</td>
					</tr>
				</tbody>
			</table>

			<div class="container">
				<div class="row" style="background-color: #17b91733;">
					<div class="col-md-12" style="text-align: center;">
						<span style="color: #af0505;">Payments should be done in the name of <b>Link Media Advertising</b></span>
					</div>
					<div class="col-md-6">
						Payment Type
					</div>
					<div class="col-md-3">
						Cheque
						<label class="checkbox">
	                     	<input type="checkbox" />
	                    	<span class="default"></span>
	                     </label>
					</div>
					<div class="col-md-3">
						Cash
						<label class="checkbox">
	                     	<input type="checkbox" />
	                    	<span class="default"></span>
	                     </label>
					</div>
					<div class="col-md-12" style="margin-top: 5%">
						  <div class="form-group row">
						    <label for="chq" class="col-sm-3 col-form-label">Cheque Number</label>
						    <div class="col-sm-9">
						      <input type="text" class="form-control" id="chq">
						    </div>
						  </div>
						  <div class="form-group row">
						    <label for="cash" class="col-sm-3 col-form-label">Cash</label>
						    <div class="col-sm-9">
						      <input type="text" class="form-control" id="cash">
						    </div>
						  </div>
						  <div class="form-group row">
						    <label for="bank" class="col-sm-3 col-form-label">Bank</label>
						    <div class="col-sm-9">
						      <input type="text" class="form-control" id="bank">
						    </div>
						  </div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<style type="text/css">
	input[type="text"],
select.form-control {
  background: transparent;
  border: none;
  border-bottom: 1px solid #000000;
  -webkit-box-shadow: none;
  box-shadow: none;
  border-radius: 0;
}

input[type="text"]:focus,
select.form-control:focus {
  -webkit-box-shadow: none;
  box-shadow: none;
}
</style>
<div class="container-fluid" style="background-color: #8080800f; margin-top: 1%;">
	<div class="row">
		<div class="col-md-6">
			<div class="form-group row">
			    <label for="name" class="col-sm-3 col-form-label">Company Name: </label>
			    <div class="col-sm-9">
			      <input type="text" class="form-control" id="name" required style="border-bottom: 1px dotted #000000;">
			    </div>
			  </div>
			  <div class="form-group row">
			    <label for="name" class="col-sm-3 col-form-label">Representative Name:</label>
			    <div class="col-sm-9">
			      <input type="text" class="form-control" id="name" required style="border-bottom: 1px dotted #000000;">
			    </div>
			  </div>
			  <div class="form-group row">
			    <label for="name" class="col-sm-3 col-form-label">Signature:
			    </label>
			    <div class="col-sm-9">
			    	<img src="" style="display: none;" id="img-rep-com" class="img-fluid" alt="Responsive image">
			      	<input type="text" data-toggle="modal" data-target="#sigRep" class="form-control" id="text-com-sig" required style="border-bottom: 1px dotted #000000;">
			    </div>
			  </div>

			  <div class="form-group row">
			    <label for="name" class="col-sm-3 col-form-label">Date:</label>
			    <div class="col-sm-9">
			      <input type="text" class="form-control" id="name" required style="border-bottom: 1px dotted #000000;">
			    </div>
			  </div>

		</div>

		<div class="col-md-6">
			<h5>Sole global advertising sales</h5>
			<h5>Link Media Advertising LLC</h5>
			<div class="form-group row">
			    <label for="name" class="col-sm-3 col-form-label">Representative Name: </label>
			    <div class="col-sm-9">
			      <input type="text" class="form-control" id="name" required style="border-bottom: 1px dotted #000000;">
			    </div>
			  </div>
			  <div class="form-group row">
			    <label for="name" class="col-sm-3 col-form-label">Signature</label>
			    <div class="col-sm-9">
			      <input type="text" class="form-control" id="name" required style="border-bottom: 1px dotted #000000;">
			    </div>
			  </div>

			  <div class="form-group row">
			    <label for="name" class="col-sm-3 col-form-label">Date:</label>
			    <div class="col-sm-9">
			      <input type="text" class="form-control" id="name" required style="border-bottom: 1px dotted #000000;">
			    </div>
			  </div>

		</div>

	</div>
</div>



<!-- Modal -->
<div class="modal fade" id="sigRep" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Signature:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<div class="rep-com"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" onclick="clearComSig()"	>Clear</button>
        <button type="button" class="btn btn-primary" onclick="addAttacthComSig()">Save changes</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
	$('.rep-com').jqSignature({width: 465});
	function clearComSig() {
		$('.rep-com').jqSignature('clearCanvas');
	}
	function addAttacthComSig(){
		$('#img-rep-com').css('display', 'block');
		$("#img-rep-com").attr("src", $('.rep-com').jqSignature('getDataURL'));
		$('.rep-com').jqSignature('clearCanvas');
		$('#text-com-sig').css('display', 'none');
		$('#sigRep').modal('toggle');
	}
</script>