<!--DOUGHNUT graph START -->
<div class="col s12 m4">
	<div class="card">
		<div class="card-header">
			<span class="card-title cyan-text text-accent-4">
				Earned Today
			</span> 
			<!-- <span class="card-title soft-text"> 
				/ 
			</span> 
			<span class="card-title amber-text text-darken-3">
				Earned Today
			</span> -->
		</div>
		<div class="divider"></div>
		<div class="card-content" style="padding:40px;">
			<!-- <canvas id="graph-doughnut" width="360" height="360"/></canvas> -->
			<h1 class="center-align amber-text text-darken-3">450 pesos</h1>
		</div>
	</div>
</div>
<!--DOUGHNUT graph END --> 