<!--DOUGHNUT graph START -->
<div class="col s12 m3">
	<div class="card">
		<div class="card-header">
			<span class="card-title cyan-text text-accent-4">
				Total Hours Today
			</span> 
			<!-- <span class="card-title soft-text"> 
				/ 
			</span> 
			<span class="card-title amber-text text-darken-3">
				Earned Today
			</span> -->
		</div>
		<div class="divider"></div>
		<div class="card-content" style="padding:40px;">
			<!-- <canvas id="graph-doughnut" width="360" height="360"/></canvas> -->
			<h1 class="center-align red-text text-darken-1">4:30:32</h1>
			<div class="progress">
				<div class="determinate" style="width: 70%"></div>
			</div>
		</div>
	</div>
</div>
<!--DOUGHNUT graph END --> 