<?php
$toggl = Core::getSingleton("toggl/handler");
$account = Core::getModel("account/account");
$dt = Core::getSingleton("system/date");
?>
<!--DOUGHNUT graph START -->
<div class="col s12 m3">
	<div class="card">
		<div class="card-header">
			<span class="card-title cyan-text text-accent-4">
				Total Hours Today
			</span> 
			<!-- <span class="card-title soft-text"> 
				/ 
			</span> 
			<span class="card-title amber-text text-darken-3">
				Earned Today
			</span> -->
		</div>
		<div class="divider"></div>
		<div class="card-content" style="padding:40px;">
			<div class="row">
				<div class="col s12 m12">
					<h1 id="todayTotalHours" class="center-align red-text text-darken-1">00:00:00</h1>
					<div class="progress">
						<div class="determinate" style="width: 70%"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--DOUGHNUT graph END --> 
<?php $this->getChildBlock("dashboard/js"); ?>