<?php
$toggl = Core::getSingleton("toggl/handler");
$account = Core::getModel("account/account");
?>
<!--DOUGHNUT graph START -->
<div class="col s12 m3">
	<div class="card">
		<div class="card-header">
			<span class="card-title cyan-text text-accent-4">
				Payday
			</span> 
			<span class="card-title soft-text"> 
				/ 
			</span> 
			<span class="card-title amber-text text-darken-3">
				Earned
			</span>
		</div>
		<div class="divider"></div>
		<div class="card-content" style="padding:40px;">
			<div class="row">
				<div class="col s12 m12">
					<h2 id="payGrandTotalHours" class="center-align red-text text-darken-1">00:00:00</h2>
					<div class="progress">
						<div class="determinate" style="width: 70%"></div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col s5 m5">
					<p class="text-panels">Earned:</p>
				</div>
				<div class="col s7 m7">
					<p class="text-panels" id="payGrandTotalEarned">0</p>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	updatePayGrandTotal();
	var payGrandTotal = setInterval(function() {
		updatePayGrandTotal();
	},  5000);
});

/**
 *	Update today hour
 */
function updatePayGrandTotal() {
	$.getJSON("<?=Core::getBaseUrl()?>api/toggl/paydayEarned", function(data) {
		$("#payGrandTotalHours").text(data.hrs);
		$("#payGrandTotalEarned").text("PHP " + data.amountEarned);
	});
}
</script>