<!-- LINE graph START -->
<div class="col s12 m8">
	<div class="card">
		<div class="card-header"> <span class="card-title secondary-color-text">Visitors </span> <span class="card-title soft-text"> / </span> <span class="card-title primary-color-text"> Sales</span> </div>
		<div class="divider"></div>
		<div class="card-content">
			<canvas id="graph-lined" height="300" width="600"></canvas>
		</div>
	</div>
</div>
<!-- LINE graph END --> 