<div class="sidebar" data-active-color="rose" data-background-color="black" data-image="<?=$this->getImage('mdb/img/sidebar-1.jpg')?>">
            <!--
        Tip 1: You can change the color of active element of the sidebar using: data-active-color="purple | blue | green | orange | red | rose"
        Tip 2: you can also add an image using data-image tag
        Tip 3: you can change the color of the sidebar with data-background-color="white | black"
            -->
            <div class="logo">
                <a href="http://www.creative-tim.com/" class="simple-text">
                    Mashapps
                </a>
            </div>
            <div class="logo logo-mini">
                <a href="<?=Core::getBaseUrl()?>" class="simple-text">
                    Ct
                </a>
            </div>
            <div class="sidebar-wrapper">
                <div class="user">
                    <div class="photo">
                        <img src="<?=$this->getImage('mdb/img/faces/avatar.jpg')?>" />
                    </div>
                    <div class="info">
                        <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                            Tania Andrew
                            <b class="caret"></b>
                        </a>
                        <div class="collapse" id="collapseExample">
                            <ul class="nav">
                                <li>
                                    <a href="#">My Profile</a>
                                </li>
                                <li>
                                    <a href="#">Edit Profile</a>
                                </li>
                                <li>
                                    <a href="<?=Core::getBaseUrl()?>account/logout">Logout</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <ul class="nav">
                    <li>
                        <a href="<?=Core::getBaseUrl()?>dashboard">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>

                    <!--
                        Tools
                        -->
                    <li>
                        <a href="<?=Core::getBaseUrl()?>tools">
                            <i class="material-icons">Tools</i>
                            <p>Tools</p>
                        </a>
                    </li>

                </ul>
            </div>
</div>