<!-- <div class="container"> -->
<div class="row">
	<div class="col s9 offset-s2">
	<table class="highlight">
        <thead>
          <tr>
              <th data-field="id">Subject</th>
              <th data-field="name">From</th>
              <th data-field="price">Date</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>Alvin</td>
            <td>Eclair</td>
            <td>May 26, 1995</td>
          </tr>
        </tbody>
      </table>
	</div>
	</div>
<!-- </div> -->