<?php $this->getChildBlock("arksystems/css") ?>
<?php $this->getChildBlock("arksystems/js"); ?>
<!-- Main Start -->
<main>
	<div class="row">
	<?php $this->getChildBlock("page/alert"); ?>
		<div class="col s5">
			<div class="col s12 card-panel">
				<div class="row primary-color form-header">
					<div class="col s12 center-align">
						<h4 class="light white-text">Queue Numbers</h4>
					</div>
				</div>
				<div class="form-body">
					<?php $this->getChildBlock("arksystems/queuelist") ?>
				</div>
			</div>
		</div>
		<div class="col s7 center-align">
			<?php $this->getChildBlock("arksystems/collection"); ?>
			<?php $this->getChildBlock("arksystems/completed"); ?>
		</div>
		</div>
	</div>
</main>
<!-- Main End -->
