<?php $this->getChildBlock("arksystems/css") ?>
<?php $this->getChildBlock("arksystems/js"); ?>
<!-- Main Start -->
<main class="valign-wrapper">
	<div class="container valign">

		<div id="login" class="row">
			<div class="col s12 m8 l6 offset-m2 offset-l3 card-panel">
				<form class="login-form">
					<div class="row primary-color form-header">
						<div class="col s12 center-align">
							<h4 class="light white-text">Select Area</h4>
						</div>
					</div>
					<div class="form-body">
						<?php $this->getChildBlock("page/alert"); ?>
						<div class="row">
							<!-- <div class="col s4 center-align">
								<a href="<?=Core::getBaseUrl()?>arksystems/index/cashier" class="waves-effect waves-light btn-large">Cashier</a>
							</div> -->
							<div class="col s6 center-align">
								<a href="<?=Core::getBaseUrl()?>arksystems/index/kitchen" class="waves-effect waves-light btn-large">Kitchen</a>
							</div>
							<div class="col s6 center-align">
								<a href="<?=Core::getBaseUrl()?>arksystems/index/sinage" class="waves-effect waves-light btn-large">Sinage</a>
							</div>
						</div>
					</div>
				</form>
				<a class="waves-effect waves-light modal-trigger left" href="#modal1" style="color: grey;">Setup</a>
			</div>
		</div>

	</div>
</main>
<!-- Main End -->

<div id="modal1" class="modal bottom-sheet">
	<div class="modal-content">
		<h4 style="color: grey;">Reset</h4>
		<a 
			href="#" onclick="softReset()" 
			class="waves-effect waves-light btn-large tooltipped" 
			data-position="top" 
			data-delay="50" 
			data-tooltip="Soft Reset will delete all items that were already completed or collected by the customer." >
				Soft Reset
		</a>
		<a 
			href="#" onclick="reset()" 
			class="waves-effect waves-light btn-large tooltipped" 
			data-position="top" 
			data-delay="50" 
			data-tooltip="Reset will delete all data from the server." >
				Reset
		</a>
		<a
			target="blank"
			href="<?=Core::getBaseUrl()?>app/code/modules/elfinder/elfinder.html"
			class="waves-effect waves-light btn-large tooltipped" 
			data-position="top" 
			data-delay="50" 
			data-tooltip="Ads images are stored here." >
				Ads
		</a>
	</div>
</div>

<script type="text/javascript">
function softReset() {
	apiUrl = '<?=Core::getBaseUrl()?>arksystems/queue/softReset';
	swal({
			title: "Are you sure?",
			text: "You will not be able to recover this data.",
			type: "warning",
			showCancelButton: true,
			confirmButtonColor: "#DD6B55",
			confirmButtonText: "Yes, soft reset it!",
			cancelButtonText: "No, cancel!",
			closeOnConfirm: false,
			closeOnCancel: false
		},
		function(isConfirm){
			if (isConfirm) {
				$.getJSON(apiUrl, function(data) {
					if( data.status == "error" ) {
						swal("Ooops!", "We have encounter some error while performing this task.");
					}
				});
				swal("Deleted!", "Completed Items was successfully deleted.", "success");
			} else {
				swal("Cancelled", "Soft Reset was canceled.", "error");
			}
		});
}

function reset() {
	apiUrl = '<?=Core::getBaseUrl()?>arksystems/queue/reset';
	swal({
			title: "Are you sure?",
			text: "You will not be able to recover this data.",
			type: "warning",
			showCancelButton: true,
			confirmButtonColor: "#DD6B55",
			confirmButtonText: "Yes, reset it!",
			cancelButtonText: "No, cancel!",
			closeOnConfirm: false,
			closeOnCancel: false
		},
		function(isConfirm){
			if (isConfirm) {
				$.getJSON(apiUrl, function(data) {
					if( data.status == "error" ) {
						swal("Ooops!", "We have encounter some error while performing this task.");
					}
				});
				swal("Deleted!", "All items was successfully deleted.", "success");
			} else {
				swal("Cancelled", "Reset was canceled.", "error");
			}
		});
}
</script>