<?php $this->getChildBlock("arksystems/css") ?>
<?php $this->getChildBlock("arksystems/js"); ?>
<!-- Main Start -->
<main class="valign-wrapper">
	<div class="container valign">

		<div id="login" class="row">
			<div class="col s12 m8 l6 offset-m2 offset-l3 card-panel">
				<form class="login-form">
					<div class="row primary-color form-header">
						<div class="col s12 center-align">
							<h4 class="light white-text">Select Area</h4>
						</div>
					</div>
					<div class="form-body">
						<?php $this->getChildBlock("page/alert"); ?>
						<div class="row">
							<div class="col s4 center-align">
								<a href="<?=Core::getBaseUrl()?>arksystems/index/cashier" class="waves-effect waves-light btn-large">Cashier</a>
							</div>
							<div class="col s4 center-align">
								<a href="<?=Core::getBaseUrl()?>arksystems/index/kitchen" class="waves-effect waves-light btn-large">Kitchen</a>
							</div>
							<div class="col s4 center-align">
								<a href="<?=Core::getBaseUrl()?>arksystems/index/sinage" class="waves-effect waves-light btn-large">Sinage</a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>

	</div>
</main>
<!-- Main End -->
