<?php $this->getChildBlock("arksystems/css") ?>
<?php $this->getChildBlock("arksystems/js"); ?>
<?php $this->getChildBlock("arksystems/sketchfont"); ?>

<style type="text/css">

.ark-container {
	margin-bottom: 0;
}

.queue-numbers {
	color: #b71c1c;
}

.primary-color {
	background-color: #37474f !important;
}

.qtxt{
	font-size: 45px;
	margin: 0px;
}

#mypanels.card-panel {
	background-color: transparent !important;
	box-shadow: none;
	padding-top: 12%;
	margin-bottom: 0px;
}

#sinageup {
	width: 90%;
	margin-left: 41px;
	margin-top: 20px;
}

#sinagedown {
	width: 99%;
	margin-left: 45px;
	margin-top: 20px;
	height: 725px;
	overflow: hidden;
}

.qtxt {
	font-family: Cabin Sketch;
	color: white;
	font-size: 145px;
	float: left;
	width: 336px;
	text-align: center;
	line-height: 1.3;
	text-shadow: 1px 1px 1px #000;
}

p.qtxt span 
{
    display: block !important;
}

.mainADS {
	margin-top: 52px;
    margin-left: 113px;
    border: 2px solid rgba(225,225,225, .18);
    -webkit-background-clip: padding-box; /* for Safari */
    background-clip: padding-box; /* for IE9+, Firefox 4+, Opera, Chrome */
}

</style>
<div class="main" style="background-image: url('<?=$this->getImage('arksystems/bg.png')?>')">
	<div class="row ark-container" style="height: 1080px">
		<div class="col s7">
			<div class="row">
				<div class="col s12 m12">
					<div class="col s12 card-panel" id="mypanels">
						<div class="row primary-color form-header">
							<div class="col s12 center-align">
								<!-- <h4 class="light white-text">Preparing</h4> -->
							</div>
						</div>
						<div class="form-body">
							<?php $this->getChildBlock("arksystems/sinagedown"); ?>
						</div>
					</div>
				</div>
				<!-- <div class="col s6 m6">
					<div class="col s12 card-panel" id="mypanels">
						<div class="row primary-color form-header">
							<div class="col s12 center-align">
								<h4 class="light white-text">Collection</h4>
							</div>
						</div>
						<div class="form-body">
							<?php #$this->getChildBlock("arksystems/sinagedown"); ?>
						</div>
					</div>
				</div> -->
			</div>
		</div>
		<div class="col s5">
			<?php $this->getChildBlock("arksystems/ads"); ?>
		</div>
	</div>
</div>