<style type="text/css">
  .login-form {
    margin-top: 10px;
  }
</style>
<div class="container">
  <div class="row">
      <form class="col s6 offset-s3 login-form">
        <div class="row">
          <div class="input-field col s12">
            <input id="email" type="email" class="validate">
            <label for="email" data-error="wrong" data-success="right">Email</label>
          </div>
        </div>
      </form>
  </div>
</div>