<?php $this->getChildBlock("index/nav"); ?>
    <div class="section section-signup page-header" style="background-image: url('<?=$this->getImage("default/img/kit/bg2.jpg")?>');">
    <div class="container">
      <?php $this->getChildBlock("page/notify"); ?>
      <div class="row">
        <div class="col-md-4 ml-auto mr-auto">
          <div class="card card-signup">
            <form name="frmLogin" class="form" method="POST" action="<?=Core::getBaseUrl()?>account/login/authenticate">
              <div class="card-header card-header-primary text-center">
                <h4>Sign In</h4>
                <div class="social-line">
                  <a href="#" class="btn btn-link btn-just-icon">
                    <i class="fa fa-facebook-square"></i>
                  </a>
                  <a href="#" class="btn btn-link btn-just-icon">
                    <i class="fa fa-twitter"></i>
                  </a>
                  <a href="#" class="btn btn-link btn-just-icon">
                    <i class="fa fa-google-plus"></i>
                  </a>
                </div>
              </div>
              <p class="text-divider">Or Be Classical</p>
              <div class="card-body">

                <span class="bmd-form-group"><div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                        <i class="material-icons">face</i>
                    </span>
                  </div>
                  <input type="text" name="user" class="form-control" placeholder="User Name..." required autocomplete="off" value="<?=isset($_GET['user']) ? $_GET['user'] : ""?>">
                </div></span>

                <span class="bmd-form-group"><div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                        <i class="material-icons">lock_outline</i>
                    </span>
                  </div>
                  <input type="password" name="pass" class="form-control" placeholder="Password..." required>
                </div></span>
              </div>
              <div class="card-footer justify-content-center">
                <input type="submit" class="btn btn-link btn-primary btn-lg" value="Get Started">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>