<?php $this->getChildBlock("page/nav"); ?>
<div class="wrapper wrapper-full-page">
		<div class="full-page login-page" filter-color="black" data-image="../../assets/img/login.jpg">
			<!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
			<div class="content">
				<div class="container">
					<?php $this->getChildBlock("page/notify"); ?>
					<div class="row">
						<div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
							<form name="frmLogin" method="POST" action="<?=Core::getBaseUrl()?>account/login/authenticate">
								<div class="card card-login card-hidden">
									<div class="card-header text-center" data-background-color="purple">
										<h4 class="card-title">Login</h4>
										<div class="social-line">
											<a href="#btn" class="btn btn-just-icon btn-simple">
												<i class="fa fa-facebook-square"></i>
											</a>
											<a href="#pablo" class="btn btn-just-icon btn-simple">
												<i class="fa fa-twitter"></i>
											</a>
											<a href="#eugen" class="btn btn-just-icon btn-simple">
												<i class="fa fa-google-plus"></i>
											</a>
										</div>
									</div>
									<p class="category text-center">
										Or Be Classical
									</p>
									<div class="card-content">
										<div class="input-group">
											<span class="input-group-addon">
												<i class="material-icons">person</i>
											</span>
											<div class="form-group label-floating">
												<label class="control-label">Username</label>
												<input type="text" class="form-control" name="user" required autocomplete="off" value="<?=isset($_GET['user']) ? $_GET['user'] : ""?>">
											</div>
										</div>
										<div class="input-group">
											<span class="input-group-addon">
												<i class="material-icons">lock_outline</i>
											</span>
											<div class="form-group label-floating">
												<label class="control-label">Password</label>
												<input name="pass" type="password" class="form-control" required="true" >
											</div>
										</div>
									</div>
									<div class="footer text-center">
										<button type="submit" class="btn btn-rose btn-simple btn-wd btn-lg">Login</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<?php $this->getChildBlock("page/footer"); ?>
		</div>
	</div>

	<script type="text/javascript">
	$().ready(function() {
		demo.checkFullPageBackgroundImage();

		setTimeout(function() {
			// after 1000 ms we add the class animated to the login/register card
			$('.card').removeClass('card-hidden');
		}, 700)
	});
</script>