<?php $this->getChildBlock("index/nav"); ?>
	<div class="section section-signup page-header" style="background-image: url('<?=$this->getImage("default/img/kit/bg2.jpg")?>');">
	<div class="container">
	  <div class="row">
		<div class="col-md-4 ml-auto mr-auto">
		  <div class="card card-signup">
			<form id="frmRegister" name="frmRegister" class="form" method="POST" action="<?=Core::getBaseUrl()?>account/login/authenticate">
			  <div class="card-header card-header-primary text-center">
				<h4>Sign Up</h4>
				<div class="social-line">
				  <a href="#" class="btn btn-link btn-just-icon">
					<i class="fa fa-facebook-square"></i>
				  </a>
				  <a href="#" class="btn btn-link btn-just-icon">
					<i class="fa fa-twitter"></i>
				  </a>
				  <a href="#" class="btn btn-link btn-just-icon">
					<i class="fa fa-google-plus"></i>
				  </a>
				</div>
			  </div>
			  <p class="text-divider">Or Be Classical</p>
			  <div class="card-body">

				<!-- Username -->
				<span class="bmd-form-group"><div class="input-group">
				  <div class="input-group-prepend">
					<span class="input-group-text">
						<i class="material-icons">face</i>
					</span>
				  </div>
				  <input type="text" name="user" id="user" class="form-control" placeholder="User Name..." required autocomplete="off" data-validetta="minLength[5]">
				</div></span>

				<!-- Email Address -->
				<span class="bmd-form-group"><div class="input-group">
				  <div class="input-group-prepend">
					<span class="input-group-text">
						<i class="material-icons">email</i>
					</span>
				  </div>
				  <input type="email" id="email" name="email" class="form-control" placeholder="Email..." required>
				</div></span>

				<!-- Password -->
				<span class="bmd-form-group"><div class="input-group">
				  <div class="input-group-prepend">
					<span class="input-group-text">
						<i class="material-icons">lock_outline</i>
					</span>
				  </div>
				  <input type="password" name="pass" id="pass" class="form-control" placeholder="Password..." required>
				</div></span>

				<!-- Password Repeat -->
				<span class="bmd-form-group"><div class="input-group">
				  <div class="input-group-prepend">
					<span class="input-group-text">
						<i class="material-icons">lock_outline</i>
					</span>
				  </div>
				  <input type="password" name="pass1" id="pass1" class="form-control" placeholder="Repeat Password..." required data-validetta="equalTo[pass]">
				</div></span>

				<!-- <div class="form-check">
					<label class="form-check-label">
						<input class="form-check-input" type="checkbox" value="">
						Subscribe to newsletter
						<span class="form-check-sign">
							<span class="check"></span>
						</span>
					</label>
				</div> -->

			  </div>
			  <div class="card-footer justify-content-center">
				<input type="submit" class="btn btn-link btn-primary btn-lg" value="Get Started">
			  </div>
			</form>
		  </div>
		</div>
	  </div>
	</div>
  </div>

<script type="text/javascript">
$( document ).ready(function() {
	$("#frmRegister").validetta();
});
	// let validate
	// $("#frmRegister").validate({
	// 	rules: {
	// 		pass: {
	// 			minlength: 5
	// 		},
	// 		pass1: {
	// 			minlength: 5,
	// 			equalTo: "#pass"
	// 		}
	// 	},
	// 	messages: {
	// 		pass: "Your password must be at least 5 characters long.",
	// 		equalTo: "Please enter the same password as above."
	// 	}
	// });
</script>