<?php $this->getChildBlock("page/preloader"); ?>
<?php $this->getChildBlock("page/navmember"); ?>
<?php $this->getChildBlock("page/icon"); ?>

<!-- Main START -->
<main>
<div class="container">
	<h1 class="thin">Dashboard</h1>
	<div id="dashboard">
		<?php $this->getChildBlock("page/alert"); ?>
		<?php $this->getChildBlock("dashboard/overview"); ?>
		<div class="row"> 
			<!-- Latest Tasks START -->
			<div class="col s12 m12">
				<div class="card hoverable">
					<ul class="collection with-header">
						<div class="collection-header primary-color" style="background-color: #546e7a !important;">
							<h5 class="light" style="color: white;">
								My Tasks
								<a href="#!" class="secondary-content tooltipped" data-position="bottom" data-delay="50" data-tooltip="View All">
									<i class="material-icons secondary-color-text">arrow_forward</i>
								</a>
							</h5>
						</div>
						<div id="tasks">
							
						</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
</main>
<!-- Main END --> 