    <div class="wrapper">
        <?php $this->getChildBlock("dashboard/navsideauth"); ?>
        <div class="main-panel">
            <?php $this->getChildBlock('dashboard/navtopauth'); ?>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <form id="RangeValidation" class="form-horizontal" action="#" method="">
                                    <div class="card-header card-header-text" data-background-color="rose">
                                        <h4 class="card-title">Welcome</h4>
                                    </div>
                                    <div class="card-content">
                                        <h1>Hello <?= $_SESSION['account']->username ?></h1>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php $this->getChildBlock("page/footer"); ?>
        </div>
    </div>