<?php $this->getChildBlock("page/navauth"); ?>
<div class="section section-signup page-header" style="background-image: url('<?=$this->getImage("default/img/kit/bg2.jpg")?>');">
    <div class="container">
      <div class="row">
      	<?php $this->getChildBlock("page/notify"); ?>
        <div class="col-md-12 ml-auto mr-auto">
          <div class="card card-signup">
            <form name="frmLogin" class="form" method="POST" action="<?=Core::getBaseUrl()?>account/login/authenticate">
              <div class="card-header card-header-primary text-center">
                <h4>Dashboard</h4>
              </div>
              <div class="card-body">

              	<h1>Welcome to Dashboard <?=Core::getSingleton("system/session")->get("account")->username?></h1>

              </div>
              <div class="card-footer justify-content-center">
                <!-- <input type="submit" class="btn btn-link btn-primary btn-lg" value="Get Started"> -->
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
<?php #$this->getChildBlock("page/footer"); ?>
<script type="text/javascript">
	$("body").addClass("signup-page");
</script>