    <div class="wrapper">
        <?php $this->getChildBlock("dashboard/navsideauth"); ?>
        <div class="main-panel">
            <?php $this->getChildBlock('dashboard/navtopauth'); ?>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <form name="frmSms" id="frmSms" class="form-horizontal" action="<?=Core::getBaseUrl()?>dashboard/sms/send" method="POST">
                                    <div class="card-header card-header-text" data-background-color="rose">
                                        <h4 class="card-title">SMS</h4>
                                    </div>
                                    <div class="card-content">
                                        <?php $this->getChildBlock("page/notify"); ?>
                                        <div class="row">
                                            <label class="col-sm-2 label-on-left">Number</label>
                                            <div class="col-sm-2">
                                                <div class="form-group label-floating">
                                                    <label class="control-label"></label>
                                                    <input class="form-control" type="number" name="number" placeholder="10 digit number" number="true" min="10" required value="<?= isset($_GET['number']) ? $_GET['number'] : "" ?>" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <label class="col-sm-2 label-on-left">Message</label>
                                            <div class="col-sm-7">
                                                <div class="form-group label-floating">
                                                    <label class="control-label"></label>
                                                    <input class="form-control" type="text" name="message" maxLength="100" value="<?= isset($_GET['message']) ? $_GET['message'] : "" ?>" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer text-center">
                                        <button type="submit" class="btn btn-rose btn-fill">Send</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php $this->getChildBlock("page/footer"); ?>
        </div>
    </div>
<script type="text/javascript">
    function setFormValidation(id) {
        $(id).validate({
            errorPlacement: function(error, element) {
                $(element).parent('div').addClass('has-error');
            }
        });
    }

    $(document).ready(function() {
        setFormValidation('#frmSms');
    });
</script>