<!-- Personal tab START -->
<div id="personal">
<form method="POST" action="<?=Core::getBaseUrl()?>admin/evaluation/addCriteria">
	<div class="form-pad">
		<div class="row">
			
			<div class="col s12">
				<div class="input-field">
					<input id="current" type="text" name="criteria" class="validate">
					<label for="current">Criteria</label>
				</div>
				<div class="buttons">
				<button class="waves-effect waves-light btn" type="submit" name="btnAddCriteria"><i class="material-icons right">done</i>add</button>
				</div>
			</div>
			<div class="col s12">
				<?php $this->getChildBlock("admin/criterialist"); ?>
			</div>
		</div>
	</div>
</form>
</div>
<!-- Personal tab END -->