<table style="margin: 15px;">
<thead>
  <tr>
      <th>Code</th>
      <th>Faculty</th>
      <th>Status</th>
      <th>Action</th>
  </tr>
</thead>

<tbody>
	<?php 
		$accountDb = Core::getModel("account/account");
		$accountDataDb = Core::getModel("account/accountdata");
		$auth = Core::getSingleton("system/session")->get("auth");
		foreach( Core::getModel("admin/evaluation")->get() as $eval ) {
			$account = Core::getModel("account/account")->where("id", $eval->account_id)->first();
			if( $accountDb->isAccountType("Dean") ) {
				$rs = $accountDataDb
					->where("account_id", $account->id)
					->where("college_dept_id", $accountDb->getDepartment($auth->id)->id)
					->exist();
				if(! $rs ) {continue;}
			}
			?>
			<tr>
				<td><?=$eval->code?></td>
				<td><?=Core::getModel("account/account")->getFullname($eval->account_id)?></td>
				<td><?=$eval->status?></td>
				<td>
					<a class="modal-trigger" href="#modal<?=$account->id?>">View</a> |
					<?php
						if( $eval->status == Core::getModel("evaluation/evaluation")::STATUS_ON_GOING ) {
							?>
							<a href="<?=Core::getBaseUrl()?>evaluation/evaluation/stop/id/<?=$eval->id?>" class="disabled">Stop</a> 
							<?php
						}else{
							?>
							<a href="<?=Core::getBaseUrl()?>evaluation/evaluation/resume/id/<?=$eval->id?>" class="disabled">Resume</a> 
							<?php 
								if( Core::getModel("account/account")->isAccountType("Admin") ) {
									?>
									|
							<a href="#modal-anal<?=$account->id?>" class="modal-trigger disabled">Analyse Result</a>
									<?php
								}

							?>

							<?php
						}
					?>
				</td>
				<!-- Modal Structure -->
				  <div id="modal<?=$account->id?>" class="modal">
				    <div class="modal-content center">
				    	<h4 style="color: #455b65;">View Evaluation Result</h4>
				    	<a href="<?=Core::getBaseUrl()?>admin/evaluation/view/student/1/id/<?=$account->id?>" class="btn" style="width: 185px;">Student</a>
				    	<a href="<?=Core::getBaseUrl()?>admin/evaluation/view/peer/1/id/<?=$account->id?>" class="btn" style="width: 185px;">Peer</a>
				    </div>
				  </div>

				  <!-- Modal Structure -->
				  <div id="modal-anal<?=$account->id?>" class="modal">
				    <div class="modal-content center">
				    	<h4 style="color: #455b65;">Decision Support System</h4>
		<div class="row">
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Decision</span>
              <!-- <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.s</p>
              <p> -->
              	<?php
              	$rs = Core::getSingleton("admin/evaluation")->getEvaluationDdsData( $eval->id, $eval->code );
              	Core::log( $rs );
              	?>
              </p>
            </div>
            <div class="card-action">
              <!-- <a href="#">This is a link</a>
              <a href="#">This is a link</a> -->
            </div>
          </div>
        </div>
      </div>
				    </div>
				  </div>


	
			</tr>
			<?php
		}
	?>
</tbody>
</table>