<div class="row">
									<form name="frmEval" id="frmEval" action="<?=Core::getBaseUrl()?>admin/evaluation/submit" method="POST">
									<div class="col s12">
<style type="text/css">
	.rad {
		display: inline;
		margin-right: 20px;
	}
</style>

										<?php
											$num = 0;
												foreach( Core::getModel("admin/criteria")->get() as $ct ) {
													?>
													<div class="row">
													<h3 style="color: #87a1ad;"><?=$ct->label?></h3>
													<hr>
													<?php

													foreach( Core::getModel("admin/subcriteria")->where("evaluation_criteria_id", $ct->id)->get() as $sct ) {
														
														?>
														<div class="input-field col s12">
															<div class="row">
																<div class="col s7"><span class="thin flow-text"><?=$sct->question?></span></div>							
																<div class="col s5">
																	<div class="rad">
																		<input name="<?=$sct->id?>" type="radio" id="5-sub-<?=$num?>" value="5" class="validate" />
																		<label for="5-sub-<?=$num?>">5</label>
																	</div>
																	<div class="rad">
																		<input name="<?=$sct->id?>" type="radio" id="4-sub-<?=$num?>" value="4" />
																		<label for="4-sub-<?=$num?>">4</label>
																	</div>
																	<div class="rad">
																		<input name="<?=$sct->id?>" type="radio" id="3-sub-<?=$num?>" value="3" />
																		<label for="3-sub-<?=$num?>">3</label>
																	</div>
																	<div class="rad">
																		<input name="<?=$sct->id?>" type="radio" id="2-sub-<?=$num?>" value="2" />
																		<label for="2-sub-<?=$num?>">2</label>
																	</div>
																	<div class="rad">
																		<input name="<?=$sct->id?>" type="radio" id="1-sub-<?=$num?>" value="1" />
																		<label for="1-sub-<?=$num?>">1</label>
																	</div>
																</div>
															</div>
													  	</div>
											
														<?php
														$num++;
													}
													?>
													</div>
													<?php
												}
											?>
									</div>
									
									<div class="input-field col s12">
										<i class="material-icons prefix">mode_edit</i>
										<textarea id="icon_prefix2" class="materialize-textarea" name="comments"></textarea>
										<label for="icon_prefix2">Comments / Suggestion</label>
									</div>

									<div class="col s12 center">
										<input type="submit" name="Submit" class="btn ">
									</div>

								</form>
								</div>

<script type="text/javascript">
	$("form#frmEval").submit(function(e){
    var bol_continue = true;
  $("input:radio.validate").each(function(){
    if($(this).attr('disabled') != 'disabled'){
      var my_parent = $(this).closest('.input-field');
      if(!$('[name='+$(this).attr('name')+']').is(':checked')){
        if($(my_parent).children('.warning').length < 1){
          $(my_parent).css("border","solid red 2px");
          $(my_parent).css("padding-top","1px");
          $('label[name='+$(this).attr('name')+']').css('top', '0.1rem');
          // $(my_parent).append('<div class="col m3 s12 warning"><div class="chip" style="background: white; border: #e4e4e4 1px solid;">Please select an option</div></div>');
        }
        bol_continue = false;
      }else{
        if($(my_parent).find('.warning').length > 0){
          $(this).parent().removeAttr("style");
          $('label[name='+$(this).attr('name')+']').removeAttr('style');
          $(my_parent).find('.warning').remove()
        }
      }
    }
  });
  if(!bol_continue){
    e.preventDefault();
    return false;
  }
});
</script>