<div class="row">
	<div class="col s12">
		<h5 style="color: #455b65;">Legend:</h5>
	</div>
	<div class="col s12">
		<table class="bordered" style="margin-bottom: 15px;">
			<thead>
				<tr>
					<th>Scale</th>
					<th>Descriptive Rating</th>
					<th>Qualitative Description</th>
				</tr>
			</thead>

			<tbody>
			<tr>
				<td>5</td>
				<td>Outstanding</td>
				<td>
					The performance almost exceeds the job requirements.
					The Faculty is an exceptional role model
				</td>
			</tr>

			<tr>
				<td>4</td>
				<td>Very Satisfactory</td>
				<td>
					The performance meets and often exceeds the job requirements
				</td>
			</tr>

			<tr>
				<td>3</td>
				<td>Satisfactory</td>
				<td>
					The performance meets job requirements
				</td>
			</tr>

			<tr>
				<td>2</td>
				<td>Fair</td>
				<td>
					The performance needs some development to meet job requirements.
				</td>
			</tr>

			<tr>
				<td>1</td>
				<td>Poor</td>
				<td>
					The faculty fails to meet job requirements
				</td>
			</tr>

			</tbody>
		</table>
	</div>
</div>