<style type="text/css">
	.side-nav li.logo {
		background-color: #4c636e;
	}
	.brand-logo {
		background-color: #638190;
	}
</style>
<!-- Header START -->
<header> 
  <!-- Navigation Bar on the top, for medium and small devices -->
  <div class="brand-logo hide-on-large-only"><img src="<?=$this->getImage('admin/logo.png');?>" alt="logo" class="logo responsive-img"></div>
  <div class="navbar-fixed hide-on-large-only">
	<nav>
	  <div class="nav-wrapper">
		<ul class="right">
		  <li class="hide-on-small-only"><a href="#search-in-modal" class="modal-trigger"><i class="material-icons">search</i></a></li>
		  <li class="hide-on-small-only"><a href="<?=Core::getBaseUrl()?>admin/account/profile"><i class="material-icons">perm_identity</i></a></li>
		  <li class="hide-on-small-only"><a href="login.html" target="_blank"><i class="material-icons">exit_to_app</i></a></li>
		  <li class="toogle-side-nav"><a href="#" data-activates="slide-menu" class="button-collapse"><i class="material-icons">menu</i></a></li>
		</ul>
	  </div>
	</nav>
  </div>
  <!-- Side Navigation - fixed for large (nice scroll with Simplebar plugin), slide/drag for medium and small devices -->
  <div id="slide-menu" class="side-nav fixed" data-simplebar-direction="vertical">
	<ul class="side-nav-main">
	  <li class="logo hide-on-med-and-down"><img src="<?=$this->getImage('admin/logo.png');?>" alt="logo" class="logo responsive-img"></li>
		<li class="side-nav-inline hide-on-med-only"> 
			<a href="<?=Core::getBaseUrl()?>account/login/exit" class="inline waves-effect tooltipped" data-position="bottom" data-delay="50" data-tooltip="Logout">
				<i class="mdi-action-exit-to-app"></i>
			</a> 
			<a href="<?=Core::getBaseUrl()?>admin/account/profile" class="inline waves-effect tooltipped" data-position="bottom" data-delay="50" data-tooltip="Profile">
				<i class="mdi-action-perm-identity"></i>
			</a> 
			<a href="#search-in-modal" class="inline waves-effect modal-trigger">
				<i class="mdi-action-search"></i>
			</a>
		</li>
	  <li><a href="<?=Core::getBaseUrl()?>admin" class="waves-effect"><i class="mdi-action-dashboard left"></i><span>Dashboard</span></a></li>
	  <li><a href="<?=Core::getBaseUrl()?>admin/evaluation" class="waves-effect"><i class="mdi-action-dashboard left"></i><span>Evaluation</span></a></li>
	  <li><a href="<?=Core::getBaseUrl()?>admin/configure" class="waves-effect"><i class="mdi-action-settings left"></i><span>Criteria</span></a></li>
	  <li><a href="<?=Core::getBaseUrl()?>admin/users" class="waves-effect"><i class="mdi-action-settings left"></i><span>Users</span></a></li>
	  
	</ul>
  </div>
  <!-- Search in Modal START -->
  <div id="search-in-modal" class="modal">
	<div class="modal-content">
	  <nav class="flat">
		<div class="nav-wrapper">
		  <form>
			<div class="input-field">
			  <input id="search" type="search" class="secondary-color-text white" style="margin:0;" required>
			  <label for="search"><i class="material-icons secondary-color-text">search</i></label>
			  <i class="material-icons modal-action modal-close">close</i> </div>
		  </form>
		</div>
	  </nav>
	</div>
	<div class="modal-footer" id="btnSearch"> <a href="#searchPeople" id class=" modal-action modal-close waves-effect waves-green btn-flat modal-trigger">Search now</a> </div>
  </div>
  <!-- Search in Modal END --> 
</header>
<!-- Header END --> 


<!-- Modal Structure -->
  <div id="searchPeople" class="modal bottom-sheet">
	<div class="modal-content">
	  <h4 style="color: #87a1ad;">Search Result</h4>
	  <div id="peoplelist" class="row">
	    <!-- Auto Populate search result -->
	  </div>
	</div>
	<div class="modal-footer">
	  <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
	</div>
  </div>

<script type="text/javascript">
	$("#btnSearch").click(function(){
	    $.getJSON("<?=Core::getBaseUrl()?>account/search/search/name/" + $("#search").val(), function(result){
	    	$("#peoplelist").empty();
	        $.each(result, function(i, field){
	        	// console.log(i);
	        	// console.log(field);

	            $("#peoplelist").append('<div class="col s6 m6"> <div class="card-panel secondary-color primary-color-text">'+ field.fname + ' ' + field.lname + '<a class="modal-trigger right" href="#" style="color: white;">View</a></div></div>');
	        });
	    });
	});
</script>