<?php
	$session = Core::getSingleton("system/session");
	$auth = $session->get("auth");
	$accountDb = Core::getModel("account/account");
	$account = $accountDb->where( "id", $auth->id )->first();
	// Core::log($account);

?>
<!-- Personal tab START -->
<div id="personal">
	<form name="frmPersonal" action="<?=Core::getBaseUrl()?>admin/account/update" method="POST" id="frmPersonal">
	<input type="hidden" name="id" value="<?=$account->id?>">
		<div class="form-pad">
			<div class="row">
				<div class="col s12 m8 push-m4">
					<!-- Personal info FIELDS -->
					<div class="input-field">
						<input id="fname" name="fname" type="text" class="validate" value="<?=$account->fname?>">
						<label for="fname">First Name</label>
					</div>
					<div class="input-field">
						<input id="lname" name="lname" type="text" class="validate" value="<?=$account->lname?>">
						<label for="lname">Last Name</label>
					</div>
					<div class="input-field">
						<input id="username" name="username" type="text" class="validate" value="<?=$account->username?>" required>
						<label for="username">Username</label>
					</div>
					<!-- <div class="input-field">
						<input id="new" type="password" class="validate">
						<label for="new">New Password</label>
					</div> -->
					<!-- <div class="input-field">
						<input id="re-type-new" type="password" class="validate">
						<label for="re-type-new">Re-type New Password</label>
					</div> -->
				</div>
				<!-- <div class="col s12 m4 pull-m8">
					<div class="form-pad center-align">
						<img class="responsive-img circle" src="<?php #$this->getImage('default/defaultprofile.jpg');?>">
						<div class="file-field input-field">
							<div class="btn no-float primary-color">
								<i class="material-icons large">file_upload</i>
								<input type="file" name="profileImage">
							</div>
							<div class="file-path-wrapper hide">
								<input class="file-path validate center-align" type="text">
							</div>
						</div>
					</div>
				</div> -->
			</div>
			<!-- Save Cancel -->
			<div class="row">
			<div class="col s12 m8 push-m4 buttons">
			<button class="waves-effect waves-light btn" type="submit" name="btnPersonalUpdate"><i class="material-icons right">done</i>Save changes</button>
			<!-- <button class="waves-effect waves-light btn blue-grey lighten-2" type="submit" name="btnCancelPersonal"><i class="material-icons right">clear</i>Cancel</button> -->
			</div>
			</div>
		</div>
	</form>
</div>
<!-- Personal tab END -->