<div class="container ">
	<div class="row ">
		<div class="col s10 ">
			<span>&nbsp</span>
		</div>
		<div class="col s2">
			<ul id="dropdown2" class="dropdown-content pull-right">
				<li>
					<a href="<?=Core::getBaseUrl()?>admin/account/profile">Profile</a>
				</li>
				<li>
					<a href="#changepassword" class="modal-trigger">Change Password</a>
				</li>
				<li>
					<a href="#changeEmail" class="modal-trigger">Change Email</a>
				</li>
			</ul>
			<a class="btn dropdown-button" href="#!" data-activates="dropdown2">Menu<i class="material-icons right">arrow_drop_down</i></a>
		</div>
	</div>
</div>


<!-- Modal Structure -->
  <div id="changeEmail" class="modal">
    <form name="frmChangeEmail" id="frmChangeEmail" method="POST" action="<?=Core::getBaseUrl()?>admin/account/changeEmail">
    	<div class="modal-content">
	      <h4 style="color: #455b65;">Change Email</h4>
			<div class="row">
				<div class="input-field col s12">
					<input id="email" type="email" name="email" class="validate" value="<?=Core::getModel("account/account")->where("id", $_SESSION['auth']->id)->first()->email?>">
         			<label for="email">Email</label>
				</div>
			</div>
	    </div>
	    <div class="modal-footer">
	      <a class="modal-action modal-close waves-effect waves-green btn-flat" href="#changeEmail">Close</a>
	      <input type="submit" class="waves-effect waves-green btn-flat" value="Update">
	    </div>
    </form>
  </div>
  <!-- Modal Structure -->
  <div id="changepassword" class="modal">
    <form name="frmChangePass" id="frmChangePass" method="POST" action="<?=Core::getBaseUrl()?>admin/account/changePassword">
    	<div class="modal-content">
	      <h4 style="color: #455b65;">Change Password</h4>
			<div class="row">
				<div class="input-field col s12">
					<input name="currentPass" id="currentPass" type="password" class="validate">
					<label for="currentPass">Current Password</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12">
					<input name="newPass" id="password" type="password" class="validate">
					<label for="password">New Password</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12">
					<input name="reNewPass" id="reNewPass" type="password" class="validate">
					<label for="reNewPass">Re-type New Password</label>
				</div>
			</div>
	    </div>
	    <div class="modal-footer">
	      <a class="modal-action modal-close waves-effect waves-green btn-flat" href="#changepassword">Close</a>
	      <input type="submit" class="waves-effect waves-green btn-flat" value="Update">
	    </div>
    </form>
  </div>

  <script type="text/javascript">
  $("#frmChangePass").validate({
        rules: {
        	currentPass: {
        		required: true,
       			minlength: 5
        	},
            password: {
        		required: true,
       			minlength: 5
      		},
      		reNewPass: {
        		required: true,
        		minlength: 5,
        		equalTo: "#password",
      		},
        },
        //For custom messages
        messages: {
            uname:{
                required: "Enter a username",
                minlength: "Enter at least 5 characters"
            },
        },
        errorElement : 'div',
        errorPlacement: function(error, element) {
          var placement = $(element).data('error');
          if (placement) {
            $(placement).append(error)
          } else {
            error.insertAfter(element);
          }
        }
     });
</script>
