<div class="container ">
	<div class="row ">
		<div class="col s10 ">
			<span>&nbsp</span>
		</div>
		<div class="col s2">
			<ul id="dropdown2" class="dropdown-content pull-right">
				<li>
					<a href="<?=Core::getBaseUrl()?>admin/account/profile">Profile<span class="badge">1</span></a>
				</li>
				<li>
					<a href="<?=Core::getBaseUrl()?>admin/account/profile">Change Password</a>
				</li>
				<li>
					<a href="<?=Core::getBaseUrl()?>admin/account/profile">Change Email</a>
				</li>
			</ul>
			<a class="btn dropdown-button" href="#!" data-activates="dropdown2">Menu<i class="material-icons right">arrow_drop_down</i></a>
		</div>
	</div>
</div>