 <!-- Search in Modal START -->
  <div id="search-in-modal" class="modal">
	<div class="modal-content">
	  <nav class="flat">
		<div class="nav-wrapper">
			<div class="input-field">
			  <input id="search" type="search" class="secondary-color-text white" style="margin:0;" required>
			  <label for="search"><i class="material-icons secondary-color-text">search</i></label>
			  <i class="material-icons modal-action modal-close">close</i> </div>
		</div>
	  </nav>
	</div>
	<div class="modal-footer" id="btnSearch"> <a href="#searchPeople" id class=" modal-action modal-close waves-effect waves-green btn-flat modal-trigger">Search now</a> </div>
  </div>
  <!-- Search in Modal END --> 
</header>
<!-- Header END --> 


<!-- Modal Structure -->
  <div id="searchPeople" class="modal bottom-sheet">
	<div class="modal-content">
	  <h4 style="color: #87a1ad;">Search Result</h4>
	  <div id="peoplelist" class="row">
	    <!-- Auto Populate search result -->
	  </div>
	</div>
	<div class="modal-footer">
	  <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
	</div>
  </div>

<!-- Modal Structure -->
<div id="modalViewPeople" class="modal">
	<div class="modal-content center">
		<h4 style="color: #455b65;">View Evaluation Result</h4>
		<a href="<?=Core::getBaseUrl()?>admin/evaluation/view/student/1/id/" id="link1" class="btn" style="width: 185px;">Student</a>
		<a href="<?=Core::getBaseUrl()?>admin/evaluation/view/peer/1/id/" id="link2" class="btn" style="width: 185px;">Peer</a>
	</div>
</div>

<script type="text/javascript">

	function fireSearch() {
		$.getJSON("<?=Core::getBaseUrl()?>account/search/search/name/" + $("#search").val(), function(result){
	    	$("#peoplelist").empty();
	    	if( result.length == 0 ) {
	    		$("#peoplelist").append('<div class="card-panel alert center">No <strong><u>'+ $("#search").val() +'</u></strong> found in our database.</div>');
	    	}else{
	    		$.each(result, function(i, field){
		            $("#peoplelist").append('<div class="col s6 m6"> <div class="card-panel secondary-color primary-color-text">'+ field.fname + ' ' + field.lname + '<a class="modal-trigger right" onclick="viewSeachPeople('+ field.id +')" href="#" style="color: white;">View</a></div></div>');
		        });
	    	}
	    });
	}

	function viewSeachPeople( elem ) {
		var link1 = document.getElementById("link1");
		var link2 = document.getElementById("link2");
		link1.setAttribute('href', "<?=Core::getBaseUrl()?>admin/evaluation/view/student/1/id/" + elem);
		link2.setAttribute('href', "<?=Core::getBaseUrl()?>admin/evaluation/view/peer/1/id/" + elem);
		$('#modalViewPeople').openModal();
		$('#searchPeople').closeModal();
	}

	$("#btnSearch").click(function(){
	    fireSearch();
	});

	$("#search").keypress(function(e) {
	    if(e.which == 13) {
	        $('#searchPeople').openModal();
	        $('#search-in-modal').closeModal();
	        fireSearch();
	    }
	});
	
</script>