<?php

?>
<table style="margin: 15px;">
<thead>
  <tr>
	  <th>Name</th>
	  <th>Faculty</th>
	  <th>Status</th>
	  <th>Action</th>
  </tr>
</thead>

<tbody>
	<?php
		foreach( Core::getModel("account/account")->get() as $account ) {
			?>
			<tr>
				<td><?=$account->fname?> <?=$account->lname?></td>
				<td><?=Core::getModel("account/accounttype")->getAccountType($account->account_type_id)->type?></td>
				<td><?= $account->status ?></td>
				<td>
					<i class="material-icons">system_update_alt</i>
					<i class="material-icons">delete</i>
					<i class="material-icons">https</i>
				</td>
			</tr>
			<?php
		}
	?>
	
</tbody>
</table>