<table style="margin: 15px;">
<thead>
  <tr>
	  <th>Name</th>
	  <th>Faculty</th>
	  <th>Status</th>
	  <th>Action</th>
  </tr>
</thead>

<tbody>
	<?php
		foreach( Core::getModel("account/account")->get() as $account ) {
			if( $account->id == $_SESSION["auth"]->id ) { continue; }
			?>
			<tr>
				<td><?=$account->fname?> <?=$account->lname?></td>
				<td><?=Core::getModel("account/accounttype")->getAccountType($account->account_type_id)->type?></td>
				<td><?= $account->status ?></td>
				<td>
					<!-- <i class="material-icons">system_update_alt</i> -->
					<!-- <a href="<?=Core::getBaseUrl()?>admin/users/delete?id=<?=$account->id?>"><i class="material-icons">delete</i></a> -->
					<?php
						if( $account->status == Core::getModel("account/account")::STATUS_DISABLED ) {
							$lockLink = Core::getBaseUrl() . "admin/users/unban?id=" . $account->id; 
						}else{
							$lockLink = Core::getBaseUrl() . "admin/users/ban?id=" . $account->id;
						}
						
					?>
					<a href="<?=$lockLink?>"><i class="material-icons">https</i></a>
				</td>
			</tr>
			<?php
		}
	?>
	
</tbody>
</table>