<?php

?>
<table style="margin: 15px;">
<thead>
  <tr>
      <th>Code</th>
      <th>Faculty</th>
      <th>Status</th>
      <th>Action</th>
  </tr>
</thead>

<tbody>
  <tr>
    <td>AWDAGNFG</td>
    <td>Eclair</td>
    <td>On-Going</td>
    <td>
    	<a href="#">View</a>
    </td>
  </tr>
  <tr>
    <td>DHDFAS</td>
    <td>Jellybean</td>
    <td>On-Going</td>
  </tr>
  <tr>
    <td>AWDAWGGHN</td>
    <td>Lollipop</td>
    <td>Ended</td>
  </tr>
</tbody>
</table>