<div class="row">
	<table class="highlight centered" style="margin-bottom: 15px;">
		<thead>
			<tr>
				<th>Name</th>
				<th>Course and Year</th>
				<th>Rating</th>
				<th>Action</th>
			</tr>
		</thead>

		<tbody>
		<?php
			$request = Core::getSingleton("url/request");
			$noOfItems = 0;
			$sumRating = 0;
			$evaluationDb = Core::getModel("evaluation/evaluation");
			$evaluationDetailsDb = Core::getModel("evaluation/evaluationdetails");
			$accountEvaluatorDb = Core::getModel("evaluation/evaluator");
			$ratingDb = Core::getModel("evaluation/rating");

			$evaluation = $evaluationDb->where("account_id", $request["id"])->first();
			$evaluationDetails = $evaluationDetailsDb->where("evaluation_id", $evaluation->id)->get();
			foreach( $evaluationDetails as $ed ) {
				Core::log( $ed );
				$accountEvaluator = $accountEvaluatorDb
					->where("id", $ed->evaluator_id)
					// ->where("type", $accountType)
					->first();
				// if( $accountEvaluator->type !== $accountType ) {continue;}
				$rating = $ratingDb->where("id", $ed->rating_id)->first();
				Core::log( $accountEvaluator );
				Core::log( $rating );
				Core::log("___________________________");

				$noOfItems++;
				$sumRating = $sumRating + $rating->ave_total;
				?>
				<tr>
					<td><?=$accountEvaluator->name?></td>
					<td><?=$evaluator->course?> <?=$evaluator->year?> year</td>
					<td><?=$rating->ave_total?></td>
					<td><a class="modal-trigger" href="#modal<?=$ed->id?>">View Comment</a></td>
					<!-- Modal Structure -->
					  <div id="modal<?=$ed->id?>" class="modal">
					    <div class="modal-content">
					      <h4 class="thin" style="color: #87a1ad;"><?=$name?>'s Comment</h4>
					      <p><?=$ed->comments?></p>
					    </div>
					    <div class="modal-footer">
					      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
					    </div>
					  </div>
					<!-- Main END --> 
				</tr>
				<?php
			}
		?>
		
		</tbody>
	</table>
</div>
<div class="row">
	<div class="col s2 offset-s9">
		<?php
		$ave = 0;
			if( $sumRating > 0 ) {
				$ave = $sumRating / $noOfItems;
			}
		?>
		<p><b>Average Rating:</b> <?=$ave?></p>
	</div>
</div>