<!-- navigation bar -->
<?php $this->getChildBlock("index/nav"); ?>

<div class="page-header header-filter clear-filter purple-filter" data-parallax="true" style="background-image: url('<?=$this->getImage("default/img/kit/bg2.jpg")?>');">
	<div class="container">
		<div class="row">
			<div class="col-md-8 ml-auto mr-auto">
				<div class="brand">
					<h1>LexiPHP</h1>
					<h3>This is a lightweight PHP framework made to simplify and organize your with MVC Pattern</h3>
				</div>
			</div>
		</div>
	</div>
</div>

