<!-- navigation bar -->
<?php $this->getChildBlock("page/nav"); ?>
<!-- main page -->
<div class="wrapper wrapper-full-page">
	<div class="full-page pricing-page" data-image="../../assets/img/bg-pricing.jpg">
		<div class="content">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-md-offset-3 text-center">
						<h2 class="title">LexiPHP</h2>
						<h5 class="description">This is a lightweight PHP framework made to simplify and organize your PHP with MVC Pattern</h5>
					</div>
				</div>
			</div>
		</div>
		<?php $this->getChildBlock('page/footer'); ?>
	</div>
</div>

<script type="text/javascript">
	$().ready(function() {
		demo.checkFullPageBackgroundImage();

		setTimeout(function() {
			// after 1000 ms we add the class animated to the login/register card
			$('.card').removeClass('card-hidden');
		}, 700)
	});
</script>