<style type="text/css">
	.bx {
		border: 1px solid red;
	}
	.banner {

	}

	.login-form {
		margin-top: 10px;
		margin-right: 50px;
	}
</style>
<div class="row">
	<div class="banner">
		<div class="col s12 m8 l8">
			<h1 class="center">Banner</h1>
			<!-- <img src="<?=$this->getImage('admin/logo.png');?>" alt="logo" class="logo responsive-img"> -->
		</div>
		<div class="col s12 m4 l4">
			<div class="login-form">
				<?php $this->getChildBlock("auth/loginform"); ?>
			</div>
		</div>
		<a href="<?=Core::getBaseUrl()?>account/resetpassword">Forgot password?</a>
	</div>
</div>