<?php $this->getChildBlock("index/style") ?>
<?php $this->getChildBlock("page/navmain") ?>
<style type="text/css">
	.start-splash-header-content {
		padding-top: 0px;
	}
</style>
<main class="no-padding">
	<div class="section white no-pad-top">
		<div class="section no-pad-bot z-depth-1 start-splash-section" style="background-color: #63818f;">
		  <div class="container start-splash-container">
			  <div class="row">
				<div class="col s12 l6">
					<div class="white-text start-splash-header-content">
						<!-- <span class="start-splash-header-text white-text">Vision & Mission</span> -->
						<!-- <h3 class="start-header-paragraph-text">VISION</h3> -->
						<h5 class="white-text ">Faculty Evaluation System Version 1.0</h5>
						<p style="text-align: justify;text-indent: 50px;">This Faculty Evaluation System is designed specifically for conducting formative and summative (end of term) evaluations of all faculty members of Eastern Samar State University Guiuan Campus. This is a systematic way to examine how well a faculty member is performing in his or her job.</p>
						
					</div>
					
					<!--<p class="center-align">
					<a class="waves-effect waves-light btn" href="#screenshots" style="margin-right:10px;margin-bottom: 5px;"><i class="mdi mdi-camera left"></i>Screenshots</a>
					
					</p>-->
				</div>
			  </div>
		  </div>
		</div>
	</div>

	<div class="section white" id="features">
		<div class="container">
			<div class="row">		
				
				<div class="col s12 m6">
					<h5 class="start text-primarycolor center">University Seal</h5>
					<p style="text-align: justify;text-indent: 50px;">The seal of the university is circular in form which bears the inscription "Eastern SamarState University". The three bars at the center forming a triangle represent themandated functions of the University are Instruction, Research and Extension. The sealof the University also contains the following symbols:</p>
						<p>a. <b>Rope</b> – for unity, coordination and discipline;</p>
						<p>b. <b>Panicle</b> – for richness in agriculture and productivity;</p>
						<p>c. <b>Scroll</b> – the flag color of Eastern Samar State University with its year of inception, 1960;</p>
						<p>d. <b>Gear</b> – for science, technology and industry and the five campuses of the university;</p>
						<p>e. <b>Torch</b> – for the unquenchable thirst of learning;</p>
						<p>f. <b>Book</b> – for the source of knowledge and wisdom;</p>
						<p>g. <b>Scallops</b> – represent the seventeen regions of the country.</p>
						
						<p style="text-align: justify;text-indent: 50px">
							The colors of the seal are green, red, golden yellow, and white;
							Blue symbolizes the noble aspiration of the University;
							Red for power, and vitality;
							Green signifies freshness, hope, and productivity;
							Golden yellow for richness of aim;
							White for purity, truth and simplicity in the conduct of the University's various programs, projects and activity.
						</p>
					
				</div>
				<div class="col s6 offset-s3 m6 center" style="">
					<img class="responsive-img" src="<?=$this->getImage("admin/logo.png")?>" class="splash-image">
				</div>
				
			</div>
			<!-- <div class="row">		
						
				<div class="col s12 m6 center hide-on-small-and-down">
					<img class="responsive-img" src="wp-content/themes/androidkioskcom/images/brand_illustration.png">
				</div>
				<div class="col s12 m6">
					<h5 class="start text-primarycolor">Customise</h5>
					<ul class="start-feature-list">
					  <li>Choice of <a href="https://kioskbrowser.userecho.com/topic/882681-themes/" target="_blank">10 themes</a></li>
					  <li>Display your logo in the toolbar</li>
					  <li>Use your brandname as the app title</li><li>Brand the <a href="https://kioskbrowser.userecho.com/topic/905825-custom-error-access-denied-pages/" target=" _blank">error &amp; access denied pages</a></li>
					  <li>Display an image/video/website <a href="https://kioskbrowser.userecho.com/topic/882581-screensaver/" target="_blank">screensaver</a> whilst the device is idle</li>
					  <li><a href="https://kioskbrowser.userecho.com/topics/2306-full-screen-mode-hiding-the-toolbar/" target="_blank">Control visibility of toolbar and system bar</a></li>
					</ul>
					<p class="start-paragraph-text text-primarycolor">We also offer a branding facility/customisation service.</p>
					<p><a href="#custom">GET MORE INFO</a></p>
					
				</div>
				<div class="col s6 offset-s3 m6 center hide-on-med-and-up">
					<img class="responsive-img" src="wp-content/themes/androidkioskcom/images/brand_illustration.png">
				</div>
			</div> -->
			<!-- <div class="row" id="features-advanced">		
				
				<div class="col s12 m6">
					<h5 class="start text-primarycolor">Advanced</h5>
					<p class="start-paragraph-text text-primarycolor">Kiosk Browser has a number of advanced features.</p>
					<ul class="start-feature-list">
					  <li><a href="https://kioskbrowser.userecho.com/topic/878500-barcode-scanning/" target="blank">Barcode Scanner</a></li>
					  <li><a href="https://kioskbrowser.userecho.com/topic/922670-nfc/" target="_blank">NFC Reader</a></li>
					  <li>Print pages using <a href="https://kioskbrowser.userecho.com/topic/876321-printing-with-google-cloud-print/" target="_blank">Google Cloud Print</a> or to <a href="https://kioskbrowser.userecho.com/topic/1090348-printing-via-bluetooth/" target="_blank">Bluetooth</a> devices via JavaScript (ESC/POS)</li>
					  <li><a href="https://kioskbrowser.userecho.com/topic/1094480-standalone-mode/" target="_blank">Standalone mode</a> (behaves like a normal default browser)</li>
					  <li>Powerful <a href="https://kioskbrowser.userecho.com/topic/847040-javascript-functions/" target="_blank">JavaScript interface</a></li>
					  <li><a href="https://kioskbrowser.userecho.com/topics/964-app-drawer/" target="_blank">App Drawer</a> to launch other apps</li>
					  <li><a href="https://kioskbrowser.userecho.com/topic/1110449-xml-import-export" target="_blank">XML Import &amp; Export</a> for copying settings to multiple devices</li>
					  <li>70+ settings to control every aspect of Kiosk Browser</li>
					</ul>
					
				</div>
				<div class="col s6 offset-s3 m6 center">
					<img class="responsive-img" src="wp-content/themes/androidkioskcom/images/advanced_illustration.png">
				</div>
				
			</div> -->
		</div>
	</div>

<!-- 	<div class="section light-green darken-1" id="custom">
		<div class="container">
			<div class="row">
				<div class="col s6 offset-s3 m6 center">
					<img class="responsive-img" src="wp-content/themes/androidkioskcom/images/customise_illustration.png">
				</div><div class="col s12 m6">
					<h5 class="start white-text">Get Branded Version</h5>
					<p class="start-paragraph-text" style="color:rgba(255, 255, 255, .8);">We offer a customisation service whereby we can create a custom version of Kiosk Browser with your logo, application name, default URL and many other default settings.</p>
					<ul style="margin-bottom: 16px;padding-left: 16px;color:rgba(255, 255, 255, .8);">
						<li style="margin: 14px 0;padding: 0;list-style: initial;font-size:14px;">Customised APK file</li>
						<li style="margin: 14px 0;padding: 0;list-style: initial;font-size:14px;">Request a new APK whenever a new version of Kiosk Browser is released</li>
						<li style="margin: 14px 0;padding: 0;list-style: initial;font-size:14px;">Fully compatible with our remote management service</li>
						<li style="margin: 14px 0;padding: 0;list-style: initial;font-size:14px;">Embed licence keys or remote registration keys</li>
						<li style="margin: 14px 0;padding: 0;list-style: initial;font-size:14px;">Embed a local start page for advanced onboarding procedures</li>
					</ul>
					<p>
						<a href="https://kioskbrowser.userecho.com/topics/75-can-i-get-a-branded-version-for-my-company/" target="_blank" class="white-text">FIND OUT MORE</a>
						<a href="https://androidkiosk.onfastspring.com/" target="_blank" class="white-text" style="padding-left: 20px;">BUY BRANDED VERSION</a>
					</p>
				</div>
				
			</div>
		</div>
	</div> -->
	
	<!-- <div class="section" id="support">
		<div class="container">
			<div class="row">
				<div class="col s12 m6">
					<h5 class="start text-primarycolor">Support &amp; Documentation</h5>
					<p class="start-paragraph-text">Our first class support is provided through our <a href="https://kioskbrowser.userecho.com/" target="_blank">Support Portal &amp; Knowledge Base</a>.</p>
					<ul style="margin-bottom: 16px;padding-left: 16px;">
						<li style="margin: 14px 0;padding: 0;list-style: initial;font-size:14px;">
							Log private support tickets
						</li>
						<li style="margin: 14px 0;padding: 0;list-style: initial;font-size:14px;">
							Post public feature requests
						</li>
						<li style="margin: 14px 0;padding: 0;list-style: initial;font-size:14px;">
							Speak to us via live chat
						</li>
						<li class="start-paragraph-text" style="margin: 14px 0;padding: 0;list-style: initial;font-size:14px;">
							Browse a wide-array of FAQs, tutorials, articles and code samples
						</li>
					</ul>
					<p class="start-paragraph-text">We live and breathe Android &amp; Kiosk Browser, we are here to help!</p>
					<p><a href="https://kioskbrowser.userecho.com/" target="_blank" class="text-primarycolor">VISIT SUPPORT PORTAL</a></p>
				</div>
				<div class="col s6 offset-s3 m6 center">
					<img class="responsive-img" src="wp-content/themes/androidkioskcom/images/support_illustration.png">
				</div>
			</div>
		</div>
	</div> -->
	
	
 
  
 
</main>
	<footer class="page-footer" style="margin-top:0px;padding-left:0px;" id="contact">
	  <!--<div class="container">
		<div class="row">
		  <div class="col l6 s12">
			<h5 class="white-text">Get in touch</h5>
			
			<div id="ue-embedded-widget"></div>
			<form class="col s12" action="https://www.android-kiosk.com/contact.php" method="post" id="contactForm">
				<div class="row">
					<div class="input-field col s6">
						<i class="mdi mdi-account-circle prefix white-text"></i>
						<input id="name" name="name" type="text" class="validate white-text">
						<label for="name" class="white-text">Name</label>
					</div>
					<div class="input-field col s6">
						<i class="mdi mdi-email prefix white-text"></i>
						<input id="email" name="email" type="email" class="validate white-text">
						<label for="email" class="white-text">Email</label>
					</div>
					<div class="input-field col s12">
						<i class="mdi mdi-pencil prefix white-text"></i>
						<textarea id="message" name="message" class="materialize-textarea white-text" style="padding-bottom: 0px;"></textarea>
						<label for="message" class="white-text">Message</label>
					</div>
					<div class="input-field col s12 offset-m6 m6 l12">
						<img src="wp-content/themes/androidkioskcom/captcha.jpg" class="right" width="45px" style="margin-top:-20px;"/>
						<i class="mdi mdi-pencil prefix white-text"></i>
						<input type="text" name="captcha" id="captcha" maxlength="6" size="6" class="validate white-text"/>
						<label for="captcha" class="white-text">Image Verification</label>
                    </div>
					<div class="col offset-s7 s5">
						<button class="btn waves-effect waves-light white light-green-text text-darken-2 right" type="submit" onclick="goog_report_conversion('index.html')">Send
							<i class="mdi mdi-send right text-darken-2"></i>
						</button>
					</div>
				</div>
			</form>
          </div>
		  
		</div>
	  </div>-->
	  <div class="footer-copyright">
		<div class="container">
		<span class="white-text">© 2017 <a href="#" class="white-text" target="_blank">ESSU</a></span>
		<a href="#" class="iubenda-nostyle no-brand iubenda-embed white-text right" title="Privacy Policy">Privacy &amp; Cookies Policy</a>
		</div>
	  </div>
	</footer>