<style type="text/css">
     header, main, footer {
      padding-left: 240px;
    }

    @media only screen and (max-width : 992px) {
      header, main, footer {
        padding-left: 0;
      }
    }
</style>
<!-- <nav> -->
  <ul id="slide-out" class="side-nav fixed">
      <li><a href="#!" class="waves-effect waves-orange accent-3">Inbox</a></li>
      <li><a href="#!" class="waves-effect waves-teal">Drafts</a></li>
      <li><a href="#!" class="waves-effect waves-teal">Sent</a></li>
      <li><a href="#!" class="waves-effect waves-teal">Trash</a></li>
  </ul>
  <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>

  <ul id="nav-mobile" class="side-nav">
    <li><a href="#!" class="waves-effect waves-orange accent-3">Inbox</a></li>
    <li><a href="#!" class="waves-effect waves-teal">Drafts</a></li>
    <li><a href="#!" class="waves-effect waves-teal">Sent</a></li>
    <li><a href="#!" class="waves-effect waves-teal">Trash</a></li>
  </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
<!-- </nav> -->