<div class="row">
	<div class="col s12">
		<div class="col s6">
			<h1>Enter Collection Number: </h1>
		</div>
		<div class="col s6 card-panel">
			<form class="login-form" name="frmCollection" id="frmCollection">
				<div class="form-body">
					<?php $this->getChildBlock("page/alert"); ?>
					<div class="row">
						<div class="input-field col s12">
							<input name="queueCollection" class="validate" id="queueCollection" type="number" min="1" max="999">
							<label for="queueCollection" class="center-align">Collection Number</label>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s6">
							<a href="#" class="btn-large waves-effect waves-light col s12" onclick="addCollection()">Enter</a>
						</div>
						<div class="input-field col s6">
							<a href="#" class="btn-large waves-effect waves-light col s12" onclick="clearFrmCollection()">Clear</a>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	function addCollection() {
		var apiUrl = "<?=Core::getBaseUrl()?>arksystems/queue/addToCollection?qnum=" + $("input#queueCollection").val();
		$.getJSON(apiUrl, function(data) {
			if( data.status == "error" ) {
				alert(data.status + ": " + data.message);
			}
			clearFrmCollection();
		});
	}

	function clearFrmCollection() {
		$("#frmCollection")[0].reset();
	}
</script>