<div class="row">
	<div class="col s12">
		<div class="col s6">
			<h1>Enter Completed Number: </h1>
		</div>
		<div class="col s6 card-panel">
			<form class="login-form" name="frmCompleted" id="frmCompleted">
				<div class="form-body">
					<?php $this->getChildBlock("page/alert"); ?>
					<div class="row">
						<div class="input-field col s12">
							<input name="queueCompleted" class="validate" id="queueCompleted" type="number">
							<label for="queueCompleted" class="center-align">Queue Number</label>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s6">
							<a href="#" class="btn-large waves-effect waves-light col s12" onclick="addCompleted()">Enter</a>
						</div>
						<div class="input-field col s6">
							<a href="#" class="btn-large waves-effect waves-light col s12" onclick="clearFrmCollection()">Clear</a>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	function addCompleted() {
		var apiUrl = "<?=Core::getBaseUrl()?>arksystems/queue/addToComplete?qnum=" + $("input#queueCompleted").val();
		$.getJSON(apiUrl, function(data) {
			if( data.status == "error" ) {
				alert(data.status + ": " + data.message);
			}
			clearFrmCompleted();
		});
	}

	function clearFrmCompleted() {
		$("#frmCompleted")[0].reset();
	}
</script>