<!--  Tables Section-->
<div id="login" class="row" >
	<div class="col s4 card-panel" style="border: 1px solid red;">
		<form class="login-form" name="frmEnterQueueNumber" id="frmEnterQueueNumber" method="POST" action="<?=Core::getBaseUrl()?>arksystems/queue/add"  >
				<div class="row primary-color form-header">
					<div class="col s12 center-align">
						<h4 class="light white-text">Enter Queue Number</h4>
					</div>
				</div>
				<div class="form-body">
					<?php $this->getChildBlock("page/alert"); ?>
					<div class="row">
						<div class="input-field col s12">
							<i class="large material-icons prefix">add_to_queue</i>
							<input name="queueNumber" class="validate" id="queueNumber" type="number" autofocus>
							<label for="queueNumber" class="center-align">Queue Number</label>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s6">
							<input type="submit" name="btnEnter" class="btn-large waves-effect waves-light col s12" value="Enter">
						</div>
						<div class="input-field col s6">
							<!-- <a href="#" id="btnClear" class="btn-large waves-effect waves-light col s12">Clear</a> -->
							<button type="reset" class="btn-large waves-effect waves-light col s12">Clear</button>
						</div>
					</div>
				</div>
			</form>		
	</div>
	<div class="col s8 card-panel">
		
	</div>
</div>
