<style type="text/css">
	/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url("<?=Core::getBaseUrl()?>skin/base/default/font/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2") format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
</style>
<!--  Tables Section-->
<div id="login" class="row">
<!-- <h1 class="thin">Login</h1> -->
	<div class="col s12 m8 l6 offset-m2 offset-l3 card-panel">
		<form class="login-form" name="frmEnterQueueNumber" method="POST" action="<?=Core::getBaseUrl()?>arksystems/queue/add"  >
			<div class="row primary-color form-header">
				<!-- <div class="col s3">
					<img src="<?php #$this->getImage('default/admin-logo-full.svg');?>" alt="logo" class="logo responsive-img-height">
				</div> -->
				<div class="col s12 center-align">
					<h4 class="light white-text">Enter Queue Number</h4>
				</div>
			</div>
			<div class="form-body">
				<?php $this->getChildBlock("page/alert"); ?>
				<div class="row">
					<div class="input-field col s12">
						<i class="large material-icons prefix">add_to_queue</i>
						<input name="queueNumber" class="validate" id="number" type="number">
						<label for="number" data-error="wrong" data-success="right" class="center-align">Queue Number</label>
					</div>
				</div>
				<div class="row">
					<div class="input-field col s6">
						<input type="submit" name="btnEnter" class="btn-large waves-effect waves-light col s12" value="Enter">
					</div>
					<div class="input-field col s6">
						<a href="#"" class="btn-large waves-effect waves-light col s12">Clear</a>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>