<div class="row">
	<h1 class="center-align">Ready to Collect</h1>
	<div class="col s12 center-align" id="sinagedown">
		<!-- Content will be automatically populated here. -->
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	var MyTimer2 = setInterval(function() {
		updateCollectionList();
	},  1000);
});

function updateCollectionList() {
	for( var i = 0; i < queueCollectionSinagedown.length; i++ ) {
		if (! $( "p#sinagedown-queue-" + queueCollectionSinagedown[i] ).length ) {
			newItem = $('<p class="qtxt" id="sinagedown-queue-'+ queueCollectionSinagedown[i] +'"> '+ queueCollectionSinagedown[i] +'</p> <br/>').hide();
			$("div#sinagedown").prepend(newItem);
			newItem.fadeIn();
		}
	}

	for( var x = 0; x < queueCompletedSinagedown.length; x++ ) {
		if( $( "p#sinagedown-queue-" + queueCompletedSinagedown[x] ).length ) {
			$( "p#sinagedown-queue-" + queueCompletedSinagedown[x] ).fadeOut(1000, function(){
				$( "p#sinagedown-queue-" + queueCompletedSinagedown[x] ).remove();
			});
			
		}
	}
}
</script>