<div class="row">
	<div class="col s12 center-align" id="sinagedown">
		<!-- Content will be automatically populated here. -->
	</div>
</div>
<audio id="audio" src="<?=Core::getBaseUrl(); ?>app/code/client/arksystems/view/tada.mp3" autostart="false" ></audio>
<script type="text/javascript">
var sound = document.getElementById("audio");
$(document).ready(function() {
	var MyTimer2 = setInterval(function() {
		updateCollectionList();
	},  1000);
});

function updateCollectionList() {
	for( var i = 0; i < queuePreparingSinageup.length; i++ ) {
		if (! $( "p#sinagedown-queue-" + queuePreparingSinageup[i] ).length ) {
			newItem = $('<p class="qtxt" id="sinagedown-queue-'+ queuePreparingSinageup[i] +'"><span>'+ queuePreparingSinageup[i] +'</span></p>').hide();
			$("div#sinagedown").prepend(newItem);
			newItem.fadeIn();
			sound.play();
		}
	}

	for( var x = 0; x < queueCompletedSinagedown.length; x++ ) {
		if( $( "p#sinagedown-queue-" + queueCompletedSinagedown[x] ).length ) {
			$( "p#sinagedown-queue-" + queueCompletedSinagedown[x] ).fadeOut(1000, function(){
				$( "p#sinagedown-queue-" + queueCompletedSinagedown[x] ).remove();
			});
		}
	}
}
</script>