<div class="row">
	<h1 class="center-align">Preparing</h1>
	<div class="col s12 center-align" id="sinageup">
		<!-- Content will be automatically populated here. -->
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	var MyTimer1 = setInterval(function() {
		updatePreparingList();
	},  1000);
});

function log( str , alert1 = false) {
	if( alert1 ) {
		alert(str);
		return;
	}
	console.log( str );
	return;
}

function updatePreparingList() {
	for( var i = 0; i < queuePreparingSinageup.length; i++ ) {
		if (! $( "span#sinage-queue-" + queuePreparingSinageup[i] ).length ) {
			newItem = $('<span class="qtxt" id="sinage-queue-'+ queuePreparingSinageup[i] +'"> '+ queuePreparingSinageup[i] +', </span>').hide();
			$("div#sinageup").prepend(newItem);
			newItem.fadeIn();
		}
	}

	for( var x = 0; x < queueCollectionSinageup.length; x++ ) {
		if( $( "span#sinage-queue-" + queueCollectionSinageup[x] ).length ) {
			$( "span#sinage-queue-" + queueCollectionSinageup[x] ).fadeOut(1000, function(){
				$( "span#sinage-queue-" + queueCollectionSinageup[x] ).remove();
			});
			
		}
	}
}
</script>