<?php 
	/**
	 * Default Header
	 */
	$this->getChildBlock("frontend/header"); 
?>

	<body>

		<?php
		if( Core::getSingleton("system/kernel")->getConfig("system")["childBlockHints"] ) {
			?>
			<style type="text/css">
				.childblockhints {
					z-index: 99999;
					border: 1px solid red;
				}
				.childBlockTextPath {
					background-color: red;
					color: white;
				}
			</style>
		<?php } ?>

		<?php
			foreach ($this->getBlocks() as $varBlocks) {
				include $varBlocks;
				echo "\n";
			}
		?>

	</body>
</html>